### ISSUE TITLE
Unable to debug any of my own apps with Xcode

### ISSUE THREAD

**Issue by thFury** [pwn20wndstuff/Undecimus#50] opened 2018-10-18 17:49 UTC
Hello. This jailbreak is not allowing me to debug anything, which is quite a problem for me.
Xcode throws this error:

"An error was encountered while attempting to communicate with this device. (The service is invalid.): Please try rebooting and reconnecting the device. (0xE8000022).".

I tried rebooting the device multiple times and jailbreaking again but nothing changed.

**Comment by Samgisaninja** [comment] 2018-10-18 19:06
So, I was unable to reproduce this as of the latest RC7, we'll look into it, but also, some suggestions:

1. Xcode does weird stuff like this all the time for me, saying the device is locked when it's actually not, saying my Apple Watch isn't paired even though it is, etc. sometimes these can be fixed by rebooting the phone, computer, or both, and re attaching

2. I didn't get your specific issue, but I did get Xcode pausing my process as if there were a breakpoint during startup. A workaround for now is to install your app, then go to the "debug" menu, and click "attach to process".

**Comment by thFury** [comment] 2018-10-18 20:02
Alright. Updating to RC7 fixed the issue (had RC6). Weird. I am getting the breakpoint too, but I got that with electra too.

If this breakpoint could be disabled it would be awesome, but clicking on continue program execution directly in Xcode works too (Not sure why you didn't think of that?).

**Comment by jakeajames** [comment] 2018-10-20 14:54
@Samgisaninja to fix the breakpointing simply type "c" and hit return, it's a normal thing that happens due to jailbreakd sending "SIGCONT" late

**Comment by Samgisaninja** [comment] 2018-10-29 00:37
@thefury unable to reproduce, please try changing lighting cables?

**Comment by thFury** [comment] 2018-10-29 19:52
@Samgisaninja The error doesn't always happen. Sometimes it does, sometimes it throws sigcont and sometimes it launches straight away. I was able to launch my app after I updated to RC7 but I did get the error once on V1. I am not sure if this is fixable.

**Comment by Cryptiiiic** [comment] 2018-11-16 17:00
@thFury closing in around 24 hours unless this is still needed.

**Closed** 2018-11-27 21:36 UTC
Labels: bug
