### ISSUE TITLE
Jailbreakd Bug(Probably webkit related)

### ISSUE THREAD

**Issue by Diam0ndCrack3d** [pwn20wndstuff/Undecimus#31] opened 2018-10-17 15:50 UTC
iPhone 6, iOS 11.3, Empty_List. Yesterday I had experienced a weird bug. It’s possible that this might be the same as another issue listed but here. When viewing content inside of YouTube for about an hour. The access to the internet was cut off completely and when I exited the application to test and see if it was just not the app itself. I tried opening Twitter and the app froze at it’s loading screen. I did read jailbreakd memory issues from what was listed and it sounds like it could be this one. Just sharing what I experienced.

**Comment by Cryptiiiic** [comment] 2018-10-17 17:19
Duplicate of #12 and #19

**Comment by Samgisaninja** [comment] 2018-10-17 17:32
Definitely duplicate, please leave a comment on #12

**Closed by Samgisaninja** 2018-10-17 17:32 UTC
Labels: bug, duplicate, known issue
