### ISSUE TITLE
failed to rootify iphone x 11.4 beta 3 in v1 

### ISSUE THREAD

**Issue by sam080** [pwn20wndstuff/Undecimus#66] opened 2018-10-20 22:46 UTC
![img_0001](https://user-images.githubusercontent.com/44328835/47261228-5530d980-d47f-11e8-832e-ec99f2e58522.PNG)

**Comment by Samgisaninja** [comment] 2018-10-21 00:33
duplicate of #14

**Closed by Samgisaninja** 2018-10-21 00:33 UTC
