### ISSUE TITLE
Home Button not responding/vibrating anymore

### ISSUE THREAD

**Issue by ZerOneX** [pwn20wndstuff/Undecimus#79] opened 2018-10-24 21:05 UTC
https://amp.reddit.com/r/jailbreak/comments/9q73ti/help_any_chance_my_home_button_not_working_has/

I just found few users complaining about the same issue.

On stock 11.3.1 the home button works fine as well on Electra 1.0.3.

Actually the iphone does not vibrate anymore.... did a new rootfs and everything works just fine..... really really strange.

Going to try Electra again to check if it will vibrate accordingly  

After 3 days more or less using unc0ver (same behavior after rc6 onwards) the HB just dies.... does not vibrate anymore.

**Comment by Samgisaninja** [comment] 2018-10-27 20:01
Since this issue persists after rebooting/device not jailbroken, this is either an iOS bug or a broken Taptic Engine. If you flip the mute switch, and can feel the device "pulse" 3 times, it's an iOS bug, and can likely be fixed by updating. If it doesn't, your Taptic Engine is bad, and you should replace it https://www.ifixit.com/Guide/iPhone+7+Taptic+Engine+Replacement/67527

**Comment by ZerOneX** [comment] 2018-10-28 00:01
did you read my post Sam? If I use rollectra for example it works flawless... if I jailbreak with electra, it work flawless.....

when I jaikbroken with unc0ver, it stopped working

**Comment by Cryptiiiic** [comment] 2018-10-29 03:35
@ZerOneX change the vibration/sound settings in the iOS settings app. Had the same issue a while back. I just had to turn it back on in settings.

**Comment by ZerOneX** [comment] 2018-10-29 11:40
it is on... man, before coming here I checked everything possible.... spent days and days restoring, testing with th0r, electra and 11.3.1 stock.... i tested with uncover rc6, 7, 8,..., 1.1.0....

**Comment by Samgisaninja** [comment] 2018-10-29 13:07
So it works now?

**Comment by ZerOneX** [comment] 2018-10-29 15:32
no man... I meant that I tried that before posting anything here!

the vibration is on but the cellphone does not vibrate on uncover... only on stock 11.3.1 or with electra/thor..

so far I prefer the uncover stability than my homebutton vibration... so I am on uncover 1.1.0, but this issue is very anoying for me!!

**Comment by Jason6189** [comment] 2018-11-06 12:58
Bro are you dumb ? When your camera is open your home button doesn’t vibrate. Retard😂😂 download CloseCam and I bet all your problems will go away. You can get it from Julio Verne repo. 

Go to the tweak compatible website and search up close cam. Your home button will always vibrate 🙂

**Comment by Samgisaninja** [comment] 2018-11-06 18:08
I’m not sure if this will work or not, but I’m closing this issue as it is not a code-level issue with unc0ver itself.

**Comment by ZerOneX** [comment] 2018-11-06 19:54
> When your camera is open your home button doesn’t vibrate. download CloseCam and I bet all your problems will go away. You can get it from https://julioverne.github.io
> 
> Go to the tweak compatible website and search up close cam. Your home button will always vibrate 
> 
> Edited by Samg_is_a_Ninja to be less offensive and provide repo link.

do you have mental problems? or having a morrow is just a hobby? 

you have no idea what you are talking about dude...

**Comment by ZerOneX** [comment] 2018-11-06 19:55
> I’m not sure if this will work or not, but I’m closing this issue as it is not a code-level issue with unc0ver itself.

for sure is related with unc0ver.... 

just switched AGAIN  to electra, and everything is working fine again...

i mean, my homebutton is working fine as it should be....

**Comment by Samgisaninja** [comment] 2018-11-06 21:59
Ok maybe not? I really don’t know what to tell you, no one else has this issue, and as long as none of us can reproduce it, we can’t really do anything about it.

**Comment by ZerOneX** [comment] 2018-11-06 22:34
my first link has another case like mine! but that is ok! you can close it as I am not using unc0ver anymore! maybe someday we will more issues like mine. Thank you for your replies!

**Closed** 2018-11-09 04:46 UTC
