### ISSUE TITLE
Reload System Daemons Still Causing Respring Loop

### ISSUE THREAD

**Issue by caisamuels** [pwn20wndstuff/Undecimus#638] opened 2019-03-01 15:03 UTC
**Describe the bug**
I still cannot reload system daemons without causing a respring loop. I tried RootFS, uninstalling all tweaks, and deleting preference files left behind from tweaks. I believe this could be related to 'NoBetaAlert' / 'LetMeBlock' because when I disable them through iCleaner, I can reload system daemons without a problem.

**Device (please complete the following information):**
 - iOS Version: iOS 12.1
 - iOS Device: iPhone 6s
 - unc0ver Version: b34

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Comment by Cryptiiiic** [comment] 2019-03-01 16:43
@caisamuels please head over to #495, this is a duplicate.

**Comment by Cryptiiiic** [comment] 2019-03-01 16:43
Duplicate of #495 , so closing.

**Closed by Cryptiiiic** 2019-03-01 16:43 UTC
Labels: bug
