### ISSUE TITLE
Witget issue

### ISSUE THREAD

**Issue by borewicz9** [pwn20wndstuff/Undecimus#727] opened 2019-03-06 14:05 UTC
iPhone 6s; iOS 12.1.1; JB b41
at witget center all stock witgets (shortcuts, battery, calendar etc.) display message "can not be loaded".

**Comment by Un4givenPG** [comment] 2019-03-06 17:38
> iPhone 6s; iOS 12.1.1; JB b41
> at witget center all stock witgets (shortcuts, battery, calendar etc.) display message "can not be loaded".

Please use the issue template and close this ticket, it is useless and won't help any of the devs fixing anything.
Secondly, your problems are  by 99% caused by incompatible tweaks you irresponsibly installed without thinking.
Thirdly, restore RootFS and wait for a full release, public betas  aren't meant for new and inexperienced users.
With regards
Un4givenPG.

**Comment by Cryptiiiic** [comment] 2019-03-06 18:46
Template not used, also didn't follow guidelines.

**Closed by Cryptiiiic** 2019-03-06 18:46 UTC
