### ISSUE TITLE
Freezes after Re-jail

### ISSUE THREAD

**Issue by palmzz** [pwn20wndstuff/Undecimus#132] opened 2018-12-01 18:12 UTC
iPhone 6 ios 11.3.1 used to be jailbroken by Electra. After reset has been jailbroken by Uncover 1.1.4 losing all tweaks. After day of usage or so it freezes. After force power-off has been rejailed again by Uncover 2. Few hours of usage device freezes again.

Never freezes with Electra before (for 2-3 months).

Please advise.

**Comment by palmzz** [comment] 2018-12-01 18:14
iOs 11.3.1

**Comment by Samgisaninja** [comment] 2018-12-06 20:34
Duplicate of #12

**Closed by Samgisaninja** 2018-12-06 20:34 UTC
