### ISSUE TITLE
Random kernel panics on all versions

### ISSUE THREAD

**Issue by mesopatamian** [pwn20wndstuff/Undecimus#1952] opened 2020-05-03 14:16 UTC
**Describe the bug**

With no specific trigger, my phone randomly having kernel panics. I check the log and I suspected there maybe some RAM management related problems JetSamEvents.
Note* I tried all JetSamEvents fixed and increasing memory limit but nothing worked.

**To Reproduce**
Completely random

**Screenshots**
None

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 6S
 - unc0ver Version: 4.3.1 and I tried all previous versions.

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce - Probably
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled - I did a rootfs restore and clean system img method restore and the same behavior 
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**

http://www.mediafire.com/file/uwqcm0x1oc1h5ln/JetsamEvent-2020-04-30-233645.ips/file

https://www.mediafire.com/file/ndhr034m0zib30t/panic-base-2020-04-30-175653.ips/file

http://www.mediafire.com/file/4taikqtahzf3fuz/panic-full-2020-05-01-142716.ips

**Comment by Cryptiiiic** [comment] 2020-05-05 17:58
Duplicate of #1890

**Comment by Cryptiiiic** [comment] 2020-05-05 17:58
@MahmoudMuhammed92 please post your panic-full in the comments of #1890 and a small summary.

**Closed as completed by Cryptiiiic** 2020-05-05 17:58 UTC
Labels: duplicate
