### ISSUE TITLE
iMessages Crash 

### ISSUE THREAD

**Issue by Mosas123** [pwn20wndstuff/Undecimus#653] opened 2019-03-02 16:03 UTC
After that I make JB it makes a crash when a I want to send a voice note on iMessages:/

**Comment by TempAccountNull** [comment] 2019-03-02 21:27
Already a duplicate of my issue: https://github.com/pwn20wndstuff/Undecimus/issues/404

**Comment by Cryptiiiic** [comment] 2019-03-04 05:19
Duplicate of #404 , so closing. User also didn't provide any info.

**Closed by Cryptiiiic** 2019-03-04 05:19 UTC
