### ISSUE TITLE
Libgcc Issue

### ISSUE THREAD

**Issue by SwedishPrxck** [pwn20wndstuff/Undecimus#641] opened 2019-03-01 20:17 UTC
Still having an install issue with libgcc. Hopefully this screencap will be of more help. It asks me to upgrade and gives me:
"ldid failed to sign libraries"
"Sub-process /usr/libexec/cydia/cydo returned an error code (1)"

I have no option to reinstall either, when I go to the package I am only given the option to install

![img_0005](https://user-images.githubusercontent.com/42725495/53663919-09641d00-3c35-11e9-8667-b70450229a66.gif)

**Comment by Cryptiiiic** [comment] 2019-03-01 21:05
@SwedishPrxck That is probably outdated. Also can you post /tmp/cydia.log so I can see if this is an unc0ver issue or not.

**Comment by SwedishPrxck** [comment] 2019-03-01 22:40
> @SwedishPrxck That is probably outdated. Also can you post /tmp/cydia.log so I can see if this is an unc0ver issue or not.

It's one of the things I've supposedly needed to update since I first jailbroke. Do i need it?

and yes, didn't know you needed it. Sorry
[cydia.log](https://github.com/pwn20wndstuff/Undecimus/files/2921318/cydia.log)

**Comment by Cryptiiiic** [comment] 2019-03-01 23:02
@SwedishPrxck The issue isn't with the jailbreak itself, radare repo is outdated. Specifically libgcc doesn't even have an arm64 slice so it won't work on iOS 11 or 12. Closing this because its not an issue with unc0ver.

**Closed by Cryptiiiic** 2019-03-01 23:02 UTC

**Comment by king4q** [comment] 2019-03-02 01:48
@SwedishPrxck i literally just experienced this issue. update Unc0ver Jailbreak Resources and then try to install libgcc if you'd like. but cant guarantee it'll work.
