### ISSUE TITLE
Failed to extract bootstrap and failed to inject library

### ISSUE THREAD

**Issue by rvsandre** [pwn20wndstuff/Undecimus#169] opened 2018-12-20 12:48 UTC
iPhone 7, iOS 11.3.1, unc0ver 2.1.0

**Comment by rvsandre** [comment] 2018-12-20 14:06
![Image](https://i.imgur.com/0MKf3VW.jpg)
![Image](https://i.imgur.com/loy1uvk.jpg)

**Comment by FivePixels** [comment] 2018-12-22 07:15
#152

**Comment by wakeupk2** [comment] 2018-12-27 06:41
Did u get fixed bro ?

**Comment by Cryptiiiic** [comment] 2019-01-07 17:15
Duplicate of #152 as previously stated by FivePixels. Closing.

**Closed by Cryptiiiic** 2019-01-07 17:15 UTC
Labels: duplicate
