### ISSUE TITLE
unable to rename system snapshot (Errno: 17) - iphone7+ 12.1

### ISSUE THREAD

**Issue by 100tomer** [pwn20wndstuff/Undecimus#402] opened 2019-02-23 00:58 UTC
while the jeailbreak process there is an error 17 that says "Unable to rename system snapshot"
filename: "JailbreakViewController.m
Line 1181

**Comment by 100tomer** [comment] 2019-02-23 09:36
Still happening in b30

**Comment by jeydm** [comment] 2019-02-25 13:19
Same issue with iPhone X on 12.1

**Comment by Samgisaninja** [comment] 2019-02-27 23:42
Duplicate of #394

**Closed by Samgisaninja** 2019-02-27 23:42 UTC
