### ISSUE TITLE
Whatsapp issue

### ISSUE THREAD

**Issue by clavl23** [pwn20wndstuff/Undecimus#1894] opened 2020-03-22 20:48 UTC
- iOS Version: 13.1.3
 - iOS Device: iPhone 11 Pro Max
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

On whatsapp I cannot send screenshots or selfie or memoji. I have tries the version 4.2.1 and I got same issue. I don't have blobs saved to cand upgrade to another version of ios.

![A5EC3133-2D80-4D67-B6D3-103BA42851E1](https://user-images.githubusercontent.com/35214517/77260171-0e0bd100-6c8f-11ea-81c2-99b469025537.png)

**Comment by moondark864** [comment] 2020-03-24 06:28
What tweaks do you have.

**Comment by clavl23** [comment] 2020-03-24 06:31
I have only two tweaks:
DLEasy (paid version from packix)
LocalIapStore

Without tweaks I got the same issue!

**Comment by moondark864** [comment] 2020-03-24 19:40
Because you have two tweaks you can restore rootfs and see if the issue is still present

**Comment by clavl23** [comment] 2020-03-24 19:41
I tried. I restoted the rootfs and I try to send all of this screenshot, selfie, pictures and memoji but the same issue. No tweaks installed!

**Comment by moondark864** [comment] 2020-03-26 03:46
If you restored rootfs and you still can’t send than it must be your phone settings or something

**Comment by clavl23** [comment] 2020-03-26 06:35
I mean that, i retorefs and jailbreak again without tweaks still not sending. If i restore the rootfs and I don't jailbreak I can use whatsapp without problems

**Comment by Burnwood1911** [comment] 2020-03-26 12:46
This is a big issue facing a lot of people on 13.1.3 I also can’t send photos or forward photos and videos

**Comment by Burnwood1911** [comment] 2020-03-26 12:47
I have tried everything 0 tweaks, restore roofs the issue is with the jailbreak itself

**Comment by clavl23** [comment] 2020-03-26 12:56
> I have tried everything 0 tweaks, restore roofs the issue is with the jailbreak itself

Same to me. I have tried a lot of things but no success to repair this issue!

**Comment by Cryptiiiic** [comment] 2020-03-28 01:22
Duplicate of #1744

**Closed as completed by Cryptiiiic** 2020-03-28 01:22 UTC
Labels: Bug, duplicate
