### ISSUE TITLE
Device Freezes and resprings 

### ISSUE THREAD

**Issue by BryanM014** [pwn20wndstuff/Undecimus#301] opened 2019-02-02 08:02 UTC
That problem being happening since the first version, my device freezes up when im using WhatsApp, Spotify or playing PUBGM even on Facetime, suddenly it starts to freeze, then i cant exit from the app or close it, just being stuck until it resprings then everything back to normal.. Im on the last version 3.0.0 b4 with the last substrate iPhone 8 11.3.1 

Edit #1: After updating to v3.0.0 b8 it keeps doing the same, now even worst, it freezes and reboot..

**Comment by sportusrcu** [comment] 2019-02-02 08:05
Latest version is v3.0.0 b8

**Comment by BryanM014** [comment] 2019-02-02 08:08
Okay, i’ll update and keep in touch in case of anything

**Comment by Cryptiiiic** [comment] 2019-02-03 01:08
@BryanM014 post diagnostic.

**Comment by BryanM014** [comment] 2019-02-03 19:33
How i can post it ?

**Comment by king4q** [comment] 2019-02-04 21:17
Make sure your on Unc0ver 3.0.0 Beta 13 & If the problem persists reply here. @BryanM014

**Comment by king4q** [comment] 2019-02-05 12:01
@Cryptiiiic please help I cannot as this is out of by abilities. @BryanM014 go to the bottom of the settings page & hit share or copy diagnostics & post it here. & make sure you are on the latest unc0ver version which at this time is 3.0.0 Beta 15.

**Comment by BryanM014** [comment] 2019-02-05 17:06
Im gonna update now, i couldn’t reply because i was busy ..

**Comment by king4q** [comment] 2019-02-05 17:14
> Im gonna update now, i couldn’t reply because i was busy ..

Okay, let me know & tag me in it when you reply. If it doesn’t work post the diagnostics log & I mentioned how to get it above 👆🏻 @BryanM014

**Comment by Cryptiiiic** [comment] 2019-02-06 16:46
@BryanM014 no one has permission to that google drive link.

**Comment by king4q** [comment] 2019-02-06 17:10
@BryanM014 please post the log on something like Dropbox or grant me access. Which I’ve already requested, or take the log & copy everything out of the ZIP & post it on something like Pastebin or post it here.

**Comment by BryanM014** [comment] 2019-02-06 22:37
@king4q @Cryptiiiic verify now and my bad tho

**Comment by king4q** [comment] 2019-02-06 22:49
@Cryptiiiic here’s a link to the code in case you can’t see it. [
https://pastebin.com/wexct5mH](url)

**Comment by Cryptiiiic** [comment] 2019-02-06 23:18
@BryanM014 remove everything from both xarold repos, it's piracy and known to have broken tweaks that freeze your device.

**Comment by BryanM014** [comment] 2019-02-07 04:06
@Cryptiiiic Done, something else besides that? i'll let you know if anything happens

**Comment by Cryptiiiic** [comment] 2019-02-13 04:53
@BryanM014 closing this tomorrow if no response.

**Comment by BryanM014** [comment] 2019-02-13 05:07
@Cryptiiiic so far after i disabled few of my tweaks like CrashReport and Flex 3, i havent had any of the problems i mentioned up there, but before that i was even having night reboots with the newer versions, im on beta 27 and nothing so far..

**Comment by Cryptiiiic** [comment] 2019-02-13 18:21
@BryanM014 any vsd crashes before?

**Comment by BryanM014** [comment] 2019-02-13 20:31
@Cryptiiiic yep, you need the diagnostics again?

**Comment by Cryptiiiic** [comment] 2019-02-14 03:15
@BryanM014 sure, and can this be closed? vsd crashes are caused by youtube tweaks.

**Comment by BryanM014** [comment] 2019-02-14 04:13
@Cryptiiiic after you see the diagnostics you can decide to close it or not.. Just let me know what to do .. 

https://drive.google.com/file/d/1OjUuGnj5U1_nr28NCY1FtvuWPRISbBFB/view?usp=drivesdk

**Comment by Cryptiiiic** [comment] 2019-02-14 17:32
@BryanM014 closing this, install cappd if you have any more freezing problems.

**Closed by Cryptiiiic** 2019-02-14 17:32 UTC
Labels: need more info
