### ISSUE TITLE
Failed to verify code signature of /private/var/installd/

### ISSUE THREAD

**Issue by Toooorch** [pwn20wndstuff/Undecimus#782] opened 2019-03-13 06:23 UTC
**Describe the bug**
Hey, 

first of all thanks for your hard work! Everything was smooth until today 👍 
I wanted to update to b45 from b43 and got this cydia impactor error 42. 
I thought it is a problem with my device since Reprovision had an issue to install unc0ver so I did **futurerestore** but this problem persist even with another devices / new apple id´s etc.
Tried everything I found on the internet but nothing worked. Any ideas? 
I remember that there was a same problem with yalu jailbreak...

**Screenshots**
![image](https://user-images.githubusercontent.com/4589728/54257621-34693d80-4560-11e9-8019-e36a37e7e0ed.png)
Screenshot is from windows but macOS is also affected.

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone X GSM
 - unc0ver Version: b45

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
Don´t have any logs, impactor does not have them?

**Comment by 0hmar** [comment] 2019-03-13 06:42
I'm actually running into the same exact issue. Even went to steps of upgrading from iOS 11.4.1 b3 to 12.1.1 b3 and still running into it on my end.

I've constantly revoked certifs and even deleting app id's but it never works.

Hopefully this is something that's fixed soon. Atleast more comfortable knowing that I'm not the only one running into this issue

for details this is what i'm on

Device
iOS Version: 12.1.1~b3
iOS Device: iPhone X 10,3
unc0ver Version: b45 (I've even attempted older versions just sitting on my computer)

**Comment by turkeyNw4ffles** [comment] 2019-03-13 07:49
Yup same I've tried reinstalling Cydia Impactor even tried it on another computer but I keep getting that same exact error.

Device
IOS Version 12.1
IOS Device iPhone Xs
unc0ver Version: b45 and b44

**Comment by JH2011** [comment] 2019-03-13 07:52
I'm getting this error as well. Tried deleting app ID and revoking certificates in Impactor and have tried resetting my system time and device time also.

I have successfully used all JB's since the beta release and this is the first time I have seen this error. I tried upgrading from b43 to b45 and that is when the error occurred. I can no longer downgrade to earlier versions without that error message either.

I'm on iOS 12.1.2 with iPhone 6s.

**Comment by travis414** [comment] 2019-03-13 07:54
Same problem here🤦‍♂️😢

**Comment by DarthPestilane** [comment] 2019-03-13 08:52
Same here

**Comment by drxrxy** [comment] 2019-03-13 08:52
I’m having this same problem.

Device: IPhone XS Max
iOS: 12.1.1b3
Unc0ver Version: b45

**Comment by alita73** [comment] 2019-03-13 09:03
Same problem, started as described by OP. The problem is only with sideloading the unc0ver app - after trying to install b45, the error appears with all other betas i tested (38-45).

The solution for me was to download the app via Tweakbox - now i'm jailbroken again :)

Device: iPhone 5s
iOS: 11.4.1

**Comment by sashayudaev** [comment] 2019-03-13 12:10
Also having this problem now.

Device: iPhone X
iOS: 12.0

**Comment by Xoombie** [comment] 2019-03-13 12:24
I solved the problem for myself. I have deleted in the Apple account all previously created passwords and then created a new one. Have again run the installation on Cydia Impactor with b45 and it worked.

**Comment by AyBeg** [comment] 2019-03-13 12:48
Same problem tyring to install b45.

Device: iPhone X
iOS: 12.1.1 beta3
Unc0er b45

And I also try like Xoombie to delete all previously created password in my Apple account, but get same "error42" like before

**Comment by cusber** [comment] 2019-03-13 12:50
same problem for ipad pro

**Comment by prashuchauhan1** [comment] 2019-03-13 12:55
Same problem tyring to install b45.

Device: iPhone Xs
iOS: 12.1
Unc0ver b45

**Comment by olixerr** [comment] 2019-03-13 12:56
i believe this is an issue with using too many certificates with reprovision.
to get past this you can either wait the 7 days for one of the certificates to become invalid or create a new apple id to use with impactor and then revoke certificates with your original id in reprovision

**Comment by prashuchauhan1** [comment] 2019-03-13 13:10
no its still giving same error.

**Comment by willy810405** [comment] 2019-03-13 13:11
Same error to install b45.

Device: iPhone 5s
iOS: 12.1.1 beta3

**Comment by JH2011** [comment] 2019-03-13 13:12
Still getting the error after revoking old app password and generating a new one. Same error with new AppleID too.

**Comment by artemtereshchenko** [comment] 2019-03-13 13:13
Same error to install b45, Phone 5s, 12.1.1 beta3.

**Comment by junglejuz** [comment] 2019-03-13 13:20
Same error also using b45, iPad mini 4, ios 12.1
Tried revoking certificates, deleting Apple ID, and creating new Apple ID.

**Comment by mprieler** [comment] 2019-03-13 13:22
could it be that using the ReProvision app (which helps you do do an automated reprovisioning after 7 days) could lead to the state that you will have too many certificates certificates?

experience the same issue iPad v6 os 12.1.1

**Comment by holyswordman** [comment] 2019-03-13 13:26
I have this problem too

**Comment by artemtereshchenko** [comment] 2019-03-13 13:30
This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new

**Comment by sashayudaev** [comment] 2019-03-13 14:02
@artemtereshchenko's solution worked for me

**Comment by willy810405** [comment] 2019-03-13 14:15
> This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
> https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new

It's work for me, thanks a lot!!

**Comment by willy810405** [comment] 2019-03-13 14:16
@artemtereshchenko It's work for me, thanks!

**Comment by JH2011** [comment] 2019-03-13 14:23
@artemtereshchenko It worked for me too, thanks

**Comment by Nuke11Proof** [comment] 2019-03-13 16:17
Also same problem for me.

**Comment by Nuke11Proof** [comment] 2019-03-13 16:18
> This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
> https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new

That’s not a solution, only it’s a online service. I think most of us want to install it via impactor and then sign in via reprovision.

**Comment by ajihenridha** [comment] 2019-03-13 17:45
i have the same problem, just wanna install watusi for my iphone 6 ios 12.1.4 (non jailbroken)
try to generate new app password from appleid.apple.com still not working, even i've tried to restore my device but same error still appears

**Comment by holyswordman** [comment] 2019-03-13 17:53
i have used ignition to install 3.0.0 b46 and it worked for me.

**Comment by prashuchauhan1** [comment] 2019-03-13 18:49
Its still not working giving same error.

**Comment by afreepenguin** [comment] 2019-03-13 18:51
Same issue with 46
iPhone X
iOS 12.1.2

**Comment by turbineseaplane** [comment] 2019-03-13 18:59
I'm relieved it's not just me - same problem on iPhone SE iOS 12.1.1

**Comment by turbineseaplane** [comment] 2019-03-13 19:00
> @pwn20wnd update to 46. Maybe it works now.

Just tried - same error at Verifying Application

**Comment by JetsetJoey** [comment] 2019-03-13 19:03
I'm suddenly & inexplicably experiencing the same problem!
I woke up this morning & for some reason my phone was in an un-jailbroken state (I presume it rebooted?). I noticed there was a new version of the UnCover ipa, so I downloaded v.45 (from v. 38). I've seemingly exhausted all avenues. This UnTethered sh*t sucks!

JailBreakers worldwide should unite to initiate a massive effort to motivate JailBreak developers to develop/release an UNTETHERED JailBreak for iOS 12. I would pay $100!!!﻿

**Comment by N0vaPixel** [comment] 2019-03-13 19:17
> 
> 
> I'm suddenly & inexplicably experiencing the same problem!
> I woke up this morning & for some reason my phone was in an un-jailbroken state (I presume it rebooted?). I noticed there was a new version of the UnCover ipa, so I downloaded v.45 (from v. 38). I've seemingly exhausted all avenues. This UnTethered sh*t sucks!
> 
> JailBreakers worldwide should unite to initiate a massive effort to motivate JailBreak developers to develop/release an UNTETHERED JailBreak for iOS 12. I would pay $100!!!

@JetsetJoey Understand your fustration but jailbreak is not like it used to be years ago.
Github, and especially issues section is not the appropriate place for this kind of comments.
If you wish support Pwn20wnd it's up to you here 👍  : https://www.patreon.com/Pwn20wnd

**Comment by Rassa09** [comment] 2019-03-13 20:42
Same problem here. I'm running Anzhuang, wondering if deinstalling will fix the issue ...
Tried already everything regarding revoking, deliting certs etc. Nothing helped so far. As an error I do get also the same pic as Tooooorch at the step "Verifying Application"

**Comment by treyson17** [comment] 2019-03-13 21:10
Same here and CC'd it on Twitter.

**Comment by nilankadesilva** [comment] 2019-03-13 21:57
I have the same problem

**Comment by mariotlemes** [comment] 2019-03-14 00:36
Thanks. Works great!

**Comment by mariotlemes** [comment] 2019-03-14 00:37
> This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
> https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new

Thanks. Work for me!

**Comment by cfheld** [comment] 2019-03-14 01:11
Same problem
iPad Air
iOS 12.1.1 b3
tried b40, 45 and 46

**Comment by Pingo90** [comment] 2019-03-14 01:48
I installed TweakBox via Safari, then i installed Unc0ver b46, (before jailbreaking disable "Reload System Daemons" option) and then jailbreak it. After the jailbreak is reinstalled delete UncOver App on Homescreen and run ICleaner Pro V7.7.2.  (Notice if you have installed ReProvision then delete it via Cydia before using ICleaner, you can reinstall ReProvision at the very end of the instruction / don´t know if its necessary but I did it). After ICleaner Respring you should be able to install Unc0ver B46 via Cydia Impactor again. Now Re-Jailbreak with option "Reload System Daemons" enabled. 
You are done.

**Comment by TeoTwawki** [comment] 2019-03-14 01:49
https://twitter.com/sbingner/status/1105917482424913920

**Comment by Toffyyy** [comment] 2019-03-14 07:07
I was stuck on the same error and tried using all the previous betas from b38-b46, none worked through impactor. 

A simple fix for this is to use something like Ignition or Tweakbox, download the jailbreak from there and proceed to install it.

Hope this helps!

Device: iPhone 6s
iOS: 12.1.2

**Comment by prashuchauhan1** [comment] 2019-03-14 12:08
> > This link helped me to install unc0ver without Cydia Impactor, iPhone 5s, 12.1.1 beta 3.
> > https://www.reddit.com/r/jailbreak/comments/b0fh6r/tutorial_installationcpp_line_42_solved/?sort=new
> 
> Thanks. Work for me!

not working in iphone 8

**Comment by piverson** [comment] 2019-03-14 15:40
iphone 8plus woke up jb gone tried to reinstall unc0ver and keep getting error 42from impactor

**Comment by ji394z0z0** [comment] 2019-03-14 18:06
i just wanna play pokemon but same problem 
iphone 8
ios 12.1.4

**Comment by ImStayFrosty** [comment] 2019-03-15 03:26
Not working on mine either.
ios 12.1.2
iphone 8plus
![image](https://user-images.githubusercontent.com/10207200/54406447-92a53600-46b0-11e9-8b8c-13497e4429fb.png)

**Comment by TeoTwawki** [comment] 2019-03-15 14:25
I don't think all the "me to" is helping anything,My understanding is apple did something that is affecting both impactor and xcode that we're having to work around atm (3rd party signing services appear to be able to install still).  lets all take a breath and just give it some time.

**Comment by mhaiyue** [comment] 2019-03-16 01:46
I'm having the same issue on my ipad air2 ios 12.1.1b3

**Comment by Voyager253** [comment] 2019-03-16 19:41
@artemtereshchenko

Thanks!
Needed a new unc0ver it seemed.
Deleting, reinstalling via web and going to profile and trusting worked.

**Comment by jassaljeevan** [comment] 2019-03-18 16:46
You can resign the app using 'iOS App Signer' and then once again install via Cydia Impactor to fix this

**Comment by marcusraymonds** [comment] 2019-04-27 11:55
After landing here, it seems a lot of people are facing a similar cydia impactor 42 error. Well, I tried each and everything that exists on the internet to solve the issue but failed. At last, I decided to give it a try with other tools and whoila! It worked. Still facing the error? Get it resolved from here: [https://cydiaimpactor.online/cydia-impactor-errors/#2_installationcpp42_error](https://cydiaimpactor.online/cydia-impactor-errors/#2_installationcpp42_error)

**Closed** 2020-03-28 12:40 UTC
Labels: bug

**Comment by luixiuno** [comment] 2020-04-04 22:49
same here but with nullximpactor iOS 13, AppValley Companion and altstore give me the same message: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.pY0dhy/extracted/Undecimus.app : 0xe8008018 (The identity used to sign the executable is no longer valid.)
