### ISSUE TITLE
Restart immeadiatly after jailbreaking

### ISSUE THREAD

**Issue by Technolord3233** [pwn20wndstuff/Undecimus#518] opened 2019-02-24 21:45 UTC
Everytime try jailbreak, it manages to load the jailbreak, then it resprings, with the loading sign. When the respring finishes, like the loading sign goes away, it restarts, without ever showing the lock screen. Therefore, Cydia crashes as my device is in its unjailbroken state. It’s an ipad 6th gen, ios 12.1

**Comment by mohammad-adk** [comment] 2019-02-24 23:06
i have a same problem like this

**Comment by tryfontheo** [comment] 2019-02-25 13:48
This better not be marked as fixed, this issue still persists in b34. I restored rootfs for b33 like Pwn advised and still getting this issue. Reload System Daemons must be turned off for it to not respring loop.

**Comment by SidMostWanted** [comment] 2019-02-27 04:18
Hello there, I had the same problem after upgrading from b27 - b34 on iOS 11.4.1, today I upgraded again to b36 with hopes that the problem would solve itself, unfortunately it didn’t. However after doing some research I was able to fix the issue with a combination of all the suggestions and information I’ve gathered, in the end it turned out to be a simpler fix than expected.

Here was my fix;

Step 1: uninstall unc0ver b34 and download b36 (first try without this step) *optional* 

Step 2: turn on Airplane Mode 
(VERY IMPORTANT , I’ve never had to use airplane mode to jailbreak before but after wasting hours trying to fix this issue without airplane mode, it proved to be a vital in this fix)

Step 3: open unc0ver 

Step 4: open Settings 

Step 5: toggle Restore RootFS *ON* - toggle Reload System Daemons *OFF* 

Step 6: toggle to the jailbreak screen and tap JailBreak 

Step 7: (after Restore RootFS is successful and the device reboots) open unc0ver, select settings again and be sure that Reload Systems Daemons is still toggled *OFF* (keep Airplane mode ON)

Step 8: Tap on Jailbreak (your phone may/will reboot a couple times during this process, keep Airplane mode ON and go through the usual jailbreaking procedure) 

I hope this fix works for you, I’ve wasted a lot of time constantly jailbreaking my device over the past couple of days only for it to reboot after 38/38 which kept my device in an unjailbroken state, it was mighty stressful. GOODLUCK everyone.

**Comment by caisamuels** [comment] 2019-03-01 16:25
> Hello there, I had the same problem after upgrading from b27 - b34 on iOS 11.4.1, today I upgraded again to b36 with hopes that the problem would solve itself, unfortunately it didn’t. However after doing some research I was able to fix the issue with a combination of all the suggestions and information I’ve gathered, in the end it turned out to be a simpler fix than expected.
> 
> Here was my fix;
> 
> Step 1: uninstall unc0ver b34 and download b36 (first try without this step) _optional_
> 
> Step 2: turn on Airplane Mode
> (VERY IMPORTANT , I’ve never had to use airplane mode to jailbreak before but after wasting hours trying to fix this issue without airplane mode, it proved to be vital in this fix)
> 
> Step 3: open unc0ver
> 
> Step 4: open Settings
> 
> Step 5: toggle Restore RootFS _ON_ - toggle Reload System Daemons _OFF_
> 
> Step 6: toggle to the jailbreak screen and tap JailBreak
> 
> Step 7: (after Restore RootFS is successful and the device reboots) open unc0ver, select settings again and be sure that Reload Systems Daemons is still toggled _OFF_ (keep Airplane mode ON)
> 
> Step 8: Tap on Jailbreak (your phone may/will reboot a couple times during this process, keep Airplane mode ON and go through the usual jailbreaking procedure)
> 
> I hope this fix works for you, I’ve wasted a lot of time constantly jailbreaking my device over the past couple of days only for it to reboot after 38/38 which kept my device in an unjailbroken state, it was mighty stressful. GOODLUCK everyone.

When do we turn 'Reload System Daemons' back on?

**Comment by Samgisaninja** [comment] 2019-03-04 00:56
Duplicate of #403

**Closed by Samgisaninja** 2019-03-04 00:56 UTC
Labels: pinned
