### ISSUE TITLE
02/24/2019 - v3.0.0~b38 Reload Daemons after RootFS Restore still failing (iphone10,6 [X] ios12.1)

### ISSUE THREAD

**Issue by MBehr2** [pwn20wndstuff/Undecimus#495] opened 2019-02-24 18:08 UTC
Issue with reloading system daemons causing the device to get stuck with a spinning wheel and eventually rebooting itself.

Not sure where to find the log files to attach for v3.0.0~b33

**Comment by VBQL** [comment] 2019-02-24 18:37
What Unc0ver version are you using? I recommend using the newest one as the changelog seems to fix an issue similar to yours.

**Comment by Sahahh** [comment] 2019-02-24 18:56
Same, even after a RootFS Restore

**Comment by JSeredick** [comment] 2019-02-25 15:03
Upvote on this issue. Worked fine the first time after having this issue, since then I have not been able to get the jailbreak to load properly, always stuck on spinning logo. I am on Undecimus-v3.0.0-b34 the newest at the time of this comment. I also tried rootfs restore with the reinstall cydia option didn't work.

**Comment by MBehr2** [comment] 2019-02-25 15:30
Tried v3.0.0~b34 - RootFS AND Airplane mode: 1st attempt kept spinning and trying to Reload Daemons  - after 20+ minutes gave up and rebooted. 2nd attempt spontaneously reboots. 3rd attempt with out Reload Daemons works fine, tho the BigBoss repo installation errors with being unsigned - a refresh fixes it.

**Comment by Cryptiiiic** [comment] 2019-02-28 06:45
Post diagnostics and crash logs.

**Comment by MBehr2** [comment] 2019-02-28 12:22
As in my very first post at the top (did you miss it?)

**### "Not sure where to find the log files to attach?"**

**Comment by Cryptiiiic** [comment] 2019-02-28 19:27
@MBehr2 Unc0ver settings, scroll down, you can't miss it the option.

**Comment by MBehr2** [comment] 2019-03-01 12:37
@Cryptiiiic Sadly the Diagnostics.plist file is of no value, other than showing versions, repos, and tweaks installed.

I'm talking about an actual log file in \var\jailbreak\log file or where ever it's stored. Daemons don't ReLoad for me, even afterRootFS Restore and only one tweak installed. So I'm just happily testing away and providing feedback and log files when asked.

So far have iPhone X, iPhone 6s jailbroken, and partially an iPad Air. Cheers

**Comment by Cryptiiiic** [comment] 2019-03-01 16:41
@MBehr2 The diagnostics file should have a jailbreak log in it, please send.

**Comment by josearg** [comment] 2019-03-02 19:25
I always do the jailbreak disabling reload system daemons and after that I do a LDRestart and all is working fine for me. And the jailbreaks is successful always. I use PowerSelector tweak to easily perform the LDRestart. Jailbreak fails when it’s doing the LDRestart so this is the workaround!

**Comment by MBehr2** [comment] 2019-03-03 04:55
> I always do the jailbreak disabling reload system daemons and after that I do a LDRestart and all is working fine for me. And the jailbreaks is successful always. I use PowerSelector tweak to easily perform the LDRestart. Jailbreak fails when it’s doing the LDRestart so this is the workaround!

Yes, in the interim, I've also been doing this addition step to Reload Daemons.

**Comment by MBehr2** [comment] 2019-03-03 05:06
> @MBehr2 The diagnostics file should have a jailbreak log in it, please send.
> Post diagnostics and crash logs.
> Post diagnostics and crash logs.

Here you are (one with Reload enabled, and the one with out it enabled)?


[Archive.zip](https://github.com/pwn20wndstuff/Undecimus/files/2922771/Archive.zip)

**Comment by Samgisaninja** [comment] 2019-03-04 00:55
Duplicate of #403

**Closed by Samgisaninja** 2019-03-04 00:55 UTC
Labels: bug, known issue
