### ISSUE TITLE
iMessage thumbnail not working 

### ISSUE THREAD

**Issue by bri-gante** [pwn20wndstuff/Undecimus#1918] opened 2020-04-03 01:00 UTC
**Describe the bug**
when sending and receiving images/video/GIFS in group text with non iPhone users the thumbnail appears as a question mark. also Memojis don't show up in iMessage on my side either. 

**To Reproduce**
Open messages and picture thumbnails are a question mark. 

**Screenshots**
![IMG_1682](https://user-images.githubusercontent.com/63081499/78313476-d3265a80-7524-11ea-92e7-1d4c55918983.PNG)
![IMG_1681](https://user-images.githubusercontent.com/63081499/78313479-d588b480-7524-11ea-9349-66d488c4aebc.jpg)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: XS MAx
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ x] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ x] this issue is present after a rootfs restore
 - [ x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment] 2020-04-03 19:15
Duplicate of #1865

**Closed as completed by Cryptiiiic** 2020-04-03 19:15 UTC
Labels: Bug, duplicate

**Comment by Malcolmevin** [comment] 2020-04-04 01:12
What font are you using ?

**Comment by bri-gante** [comment] 2020-04-04 01:15
KG blank space sketch

**Comment by Malcolmevin** [comment] 2020-04-04 06:42
Thanks 🙌🏾 Are you using A-font I don't see it on there ?

**Comment by bri-gante** [comment] 2020-04-04 09:47
DL iFont and font manager from the App Store. I got the font from iFont.
