### ISSUE TITLE
v2.1.1 update doesn't load daemons

### ISSUE THREAD

**Issue by KMamedoff** [pwn20wndstuff/Undecimus#223] opened 2019-01-12 22:19 UTC
I have a daemon for changing resolution and it does not load at all.

**Comment by KMamedoff** [comment] 2019-01-13 20:00
@pwn20wndstuff Still isn't fixed with 2.1.1 final update.

**Comment by MannerRev** [comment] 2019-01-14 00:43
I also have this issue with the daemons from SetRes. This issue was present in versions <2.1.0 but fixed in 2.1.0 final, then broken again in 2.1.1 final.

**Comment by KMamedoff** [comment] 2019-01-14 00:44
> I also have this issue with the daemons from SetRes. This issue was present in versions <2.1.0 but fixed in 2.1.0 final, then broken again in 2.1.1 final.

Yeap. It happened on some beta versions of 2.1.0 and fixed eventually but came back with 2.1.1.

**Comment by MannerRev** [comment] 2019-01-14 00:46
Definitely works in 2.1.0 final 100% reliably and I had zero issues with that over many many restarts and rejailbreaks.

**Comment by MannerRev** [comment] 2019-01-17 03:12
Sure. Just rebooted my phone and jailbroke with u0 2.1.1 final and SetRes daemons didn't successfully load. 

Log: [diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2767009/diagnostics.txt)

**Comment by sbingner** [comment] 2019-01-19 05:48
Sorry I forgot to reply - I looked at the log and it did load it.  Must be some reason it just didn’t work.  I’ve never had ssh not work and it is loaded the same way.  I think this is an issue with SetRes...

**Comment by MannerRev** [comment] 2019-01-19 06:46
I did some probing into the daemon and it seems it's just a simple script that swaps (via /bin/cp) the com.apple.iokit.IOMobileGraphicsFamily.plist with a second one in the same directory that has the target resolution (which was set by the user). 

I'll attach the .plist for the daemons of setres -- they're really quite simple.

[com.horizon.setres.setrestarget.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2775270/com.horizon.setres.setrestarget.plist.txt)
[com.horizon.setres.setresoriginal.plist.txt](https://github.com/pwn20wndstuff/Undecimus/files/2775271/com.horizon.setres.setresoriginal.plist.txt)

I see other daemons in /Library/LaunchDaemons/, such as PlsNoOCSP and ssh as you mentioned, which are both loading just fine.

**Comment by MannerRev** [comment] 2019-01-19 06:51
I also want to note that resolution changing was working in 2.0.1 and then broken in 2.0.2 release. The first pre-release of 2.1.0 included notes stating "Fix a bug in loading daemons". Whatever this fix applied was, it fixed setres after the regression in 2.0.2.

**Comment by MannerRev** [comment] 2019-01-19 07:14
Just did a test where running a `launchctl load com.horizon.setres.setrestarget.plist && ldrestart` successfully adjusts my phone's resolution as expected, so I confirmed the daemon properly functions when loaded manually.

**Comment by KMamedoff** [comment] 2019-01-19 09:31
> Sorry I forgot to reply - I looked at the log and it did load it. Must be some reason it just didn’t work. I’ve never had ssh not work and it is loaded the same way. I think this is an issue with SetRes...

It can be loaded manually with no problem. It used to work with previous versions of unc0ver. There is no problem with SetRes, unc0ver is the problem in this case.

**Comment by sbingner** [comment] 2019-01-19 18:54
That’s probably the problem - it doesn’t actually run a daemon but pretends it does.  Probably a race condition with ldrestart.  That is not what launchdaemons are for.

**Closed by sbingner** 2019-01-19 18:54 UTC
Labels: need more info

**Comment by KMamedoff** [comment] 2019-01-19 19:04
So it has been working for months and now it stops working with new updates and it’s not a bug but a feature?

**Comment by MannerRev** [comment] 2019-01-19 19:08
I don't see how it would be a race condition. It just swaps a file. Once the file is swapped, the ldrestart could take place any time, right? And the ldrestart doesn't happen until all daemons have been loaded, including SetRes.

**Comment by sbingner** [comment] 2019-01-19 19:21
> I don't see how it would be a race condition. It just swaps a file. Once the file is swapped, the ldrestart could take place any time, right? And the ldrestart doesn't happen until all daemons have been loaded, including SetRes.

Because *loading* a daemon does not start it.  Launchd will run those commands at some unknown time after launchctl load executes.  Launch daemons are not for “cp” commands, they are for running processes.  If you want something to execute on every jailbreak it should go in /etc/rc.d

**Comment by sbingner** [comment] 2019-01-19 19:32
Because there was a pointless sleep before the ldrestart.  Fixing this is on the author of SetRes.
