### ISSUE TITLE
Device reboots when powering off.

### ISSUE THREAD

**Issue by MattieThurlow96** [pwn20wndstuff/Undecimus#123] opened 2018-11-25 22:56 UTC
Each time I slide to power off it just simply reboots instead. 
Once it’s into non jailbroken mode I can actually power down, though. 
Is this happening to anyone else at all?

iPhone 8 Plus (iOS 11.4b3)

**Comment by Cryptiiiic** [comment] 2018-11-26 18:05
Duplicate of #11

**Closed** 2018-11-29 15:46 UTC
Labels: bug, duplicate, known issue
