### ISSUE TITLE
offsetcache.h file not found

### ISSUE THREAD

**Issue by alekye** [pwn20wndstuff/Undecimus#1446] opened 2019-09-09 06:43 UTC
**Describe the bug**
I clone the project to local, and run the Undecimus.xcodeproj with xcode, a error was occurred : 'offsetcache.h' file not found.

My iPhone is : iPhone 6s plus

**Comment by vegerot** [comment] 2019-09-11 18:55
Same problem here

**Comment by margus-lind-ctx** [comment] 2019-09-16 12:59
Try recursive clone.
Dupe of #939 ?

**Comment by vegerot** [comment] 2019-09-16 22:10
Oops.  Answered it myself on another thread but forgot to post the answer here too

> Not working for me :(. Would someone be able to upload and post the file on their own?
> 
> Edit: While `git submodule update` doesn't work, recloning the repo with `git clone --recursive` does work 🤷🏽‍♀️

**Closed as completed** 2020-03-28 13:02 UTC
Labels: Bug
