### ISSUE TITLE
ALARM CLOCK BUG

### ISSUE THREAD

**Issue by Marinamoina** [pwn20wndstuff/Undecimus#292] opened 2019-01-31 09:20 UTC
An ALARM CLOCK BUG is causing my iPhone 8, 11.3.1, unc0ver 2.1.3 in a complete freeze. The alarm is on and I cannot stop it. Touch and hard buttons do not work. Only a hard reset can help.
Can u please have a look at this?
No clock tweaks installed by the way.

**Comment by Marinamoina** [comment] 2019-01-31 12:31
The issue happens randomly. Especially after a night in the morning.

**Comment by gnawh** [comment] 2019-02-01 07:59
stackxi

**Comment by Marinamoina** [comment] 2019-02-01 22:20
I don’t use StackXI.

**Comment by king4q** [comment] 2019-02-04 21:20
This issue is a duplicated of the closed issue #289. @Cryptiiiic please close this issue.

**Comment by Cryptiiiic** [comment] 2019-02-05 03:58
@king4q 289 came after this issue, it was a duplicate of this.

**Closed** 2019-02-05 03:58 UTC

**Comment by Marinamoina** [comment] 2019-02-05 06:49
It seems duplicated because the was a written mistake „Cock“ instead of „Clock“. So I closed it my self. Couldn’t delete it edit.
Please reaktivate this issue. Today morning I had a freeze again, no sound just vibration. Left the phone until Safe Mode came.

**Comment by king4q** [comment] 2019-02-05 12:22
@Marinamoina please update to Unc0ver 3.0.0 Beta 15 which is the latest at the time of typing this. & if the problem persists please post your diagnostics log.
