### ISSUE TITLE
Stuck on respring logo

### ISSUE THREAD

**Issue by sololau00** [pwn20wndstuff/Undecimus#420] opened 2019-02-23 10:28 UTC
After Success Jailbreak then sometimes respring loop then reboot the Phone.
Iphone 7 plus 9,4 A10
Ios 12.1.2
Version:Beta30
(Request)
After jaikbreak succeed disable reload system daemons

**Comment by alpgokcek** [comment] 2019-02-23 12:52
I have the same issue too... 
iPhone X 
iOS 12.1.1
version:beta 30

**Comment by rayyan-a** [comment] 2019-02-23 13:30
go to unc0ver settings and turn off reload system daemons

**Comment by tryfontheo** [comment] 2019-02-23 14:54
Also having this issue. Occurs on all three devices of mine, even without tweaks installed on 2/3. Sent tweet to Pwn with video of it here: 
https://twitter.com/tryfontheo/status/1099320738136375296

**Comment by pbr0ck3r** [comment] 2019-02-23 15:34
Can confirm I have the same issue. Iphone X - iOs 12.1.1. Disabling reload system daemons seem to work for me.

**Comment by sololau00** [comment] 2019-02-23 15:36
Tjsnks

**Comment by pbr0ck3r** [comment] 2019-02-23 15:38
@sololau00 I would still consider this a issue... by default the Restart System Daemons is turned on. Why will cause a lot of people headaches if they don't come to github and search and find this thread.

**Comment by sololau00** [comment] 2019-02-23 15:39
😂😂

**Comment by tsxmichael** [comment] 2019-02-23 18:26
Enable reinstall cydia and reset cydia cache and jailbreak

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pbr0ck3r** [comment] 2019-02-23 18:41
That just messed up my cydia. Now non of my repo's will show packages. Even after refreshing.

**Comment by pbr0ck3r** [comment] 2019-02-23 18:43
Overall I have had mixed results with having `Restart System Daemons` on. Sometimes it works. Sometimes it fails (restarts the phone).

**Comment by tsxmichael** [comment] 2019-02-23 18:45
😑first person that said that of all i been helping!! Best u can do is downgrade to the beta was working before 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tsxmichael** [comment] 2019-02-23 19:38
if you see when you do that method in the first try will stop by 16 of 38 then the second one will stop by 27/38 then should work perfectly! I been helping alot people in Twitter and its been working! Same as I recommend to downgrade to the last version that was working for them before

**Comment by pbr0ck3r** [comment] 2019-02-23 19:50
Ultimately disabling the `Restart Sytem Daemon` is the only thing that does not cause the phone to reboot when it is done jailbreaking. With it enabled... the phone just sits in respring when it is done jailbreaking or restarts

**Comment by pbr0ck3r** [comment] 2019-02-24 03:29
@tsxmichael is ZoTTD/MacCiti a default repo? If so could you get me the url? I believe I deleted it by accident

**Comment by hmoghani** [comment] 2019-02-24 15:58
I have the same issue. I jailbroke the phone successfully. Installed some tweaks. The respring works after each tweak got installed. then I reboot the phone. Hit jailbreak again, it goes to respringing, and gets stuck there ( sometimes it reboots while respringing). The only times I could get it to jailbreak and respring successfully was to enable re-install cydia and jailbreak. (doesn't work all the time though)

**Comment by Samgisaninja** [comment] 2019-02-27 23:57
Duplicate of #403

**Closed by Samgisaninja** 2019-02-27 23:57 UTC
