### ISSUE TITLE
IPhone 8 Plus IOS 12.1 uncover 3.0.0b37 line:1188

### ISSUE THREAD

**Issue by Gerardo323** [pwn20wndstuff/Undecimus#633] opened 2019-03-01 08:20 UTC
#pinned
Need help 
And info 
Please 
https://cdn.discordapp.com/attachments/349251947192254466/550934863813804032/image0.png

When trying to jailbreak and trying to restore RootFS on an iPhone 8 Plus  @ iOS 12.1 unc0ver fails because RootFS is already mounted.
There is no OTA file on the iPhone
  "shapshotSystemVersion"? 

Also updates doesn’t work never used a ota blocker

**Comment by Gerardo323** [comment] 2019-03-01 08:29
Previously I had iOS 11.3.1 with Electra accidentally updated to iOS 12.1 stayed on it till a jailbreak came out and that happened

**Comment by Cryptiiiic** [comment] 2019-03-01 16:16
@Gerardo323 You didn't follow the guidelines, one of thing from the check list said to check for if the issue already exist before posting. Please read the guidelines next time #627.

Duplicate of #629 , so closing.

**Closed by Cryptiiiic** 2019-03-01 16:16 UTC
