### ISSUE TITLE
Can’t find “iOS update”

### ISSUE THREAD

**Issue by JARBRW** [pwn20wndstuff/Undecimus#1777] opened 2020-02-23 04:22 UTC
I can’t find the “iOS update” in my iPhone Storage

**Comment by Beastandcool** [comment] 2020-02-24 05:50
be more descriptive... There were instructions on how to make a post, follow them next time. What iOS/unc0ver version are you on, could it be a tweak removing it?

**Comment by miguelr4720** [comment] 2020-02-27 00:28
THIS IS RIDICULOUS CLOSED THIS CASE

**Comment by miguelr4720** [comment] 2020-02-27 00:29
PLEASE CLOSED NOT URGENT UPDATE ARE NOT SUPPOSED TO WORK BEING JAILBROKEN 
JUST FOR PRECAUTION THE iOS Wont get Updated and LOSE JAILBRAKE

**Comment by miguelr4720** [comment] 2020-02-27 00:29
CLOSED THIS CASE LOL NOT A BUG

**Closed as completed** 2020-03-28 13:10 UTC
Labels: Bug
