### ISSUE TITLE
Restart by no reason

### ISSUE THREAD

**Issue by luixiuno** [pwn20wndstuff/Undecimus#1929] opened 2020-04-08 14:09 UTC
**Describe the bug**

**To Reproduce**
There are no steps, I got jailbreak and then randomly  in a random time I reboot

**Screenshots**
No screenshots, just restarts at an unexpected time

**Device (please complete the following information):**
 - iOS Versión: 13.3 build 17C54 
 - iOS Device: iPad Air 6,11
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce (note: I probably don’t know I am not an expert but at least I know how to jailbreak and use iOS)
 - [x ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Cryptiiiic** [comment] 2020-04-08 22:26
Duplicate of #1890

**Closed as completed by Cryptiiiic** 2020-04-08 22:26 UTC
Labels: Bug, duplicate
