### ISSUE TITLE
iPhone X Repsring Loop when headphones connected

### ISSUE THREAD

**Issue by harshmaniyar** [pwn20wndstuff/Undecimus#932] opened 2019-04-09 19:33 UTC
**Describe the bug**
Its a very wired bug, everytime i plug in my headphones to the iPhone its goes in to repsring loop and have to hard reset and re jailbreak the phone again.

**Device (please complete the following information):**
 - iOS Version: 11.3.1
 - iOS Device: iPhone X
 - unc0ver Version: 3.0.0b~49

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by xMilesManx** [comment] 2019-04-09 21:00
This is probably a tweak problem and not related to the jailbreak code. What do you have installed that could be related? Anything that that could possible affect maybe the audio or the volume HUD

**Comment by harshmaniyar** [comment] 2019-04-09 21:12
Greetings,
Booom! I had MELIOR installed as the volume HUD tweak.
Disabled it, plugged in headphones multiple times and the problem seems to have gone.
Thank you very much for the prompt help.

What do you think i should do ? Write to the tweak author about the issue.?

Thank you
Harsh Maniyar

**Comment by xMilesManx** [comment] 2019-04-09 21:14
Yes definitely reach out to the developer via email or on Twitter. 

Check out  Sonus as my favorite alternative. 

You might want to close this is it’s not related to the code of the jailbreak itself. 

Good luck!

**Comment by harshmaniyar** [comment] 2019-04-12 20:55
Hello,
Although we closed the tab but i think my issue really hasnt been solved.
I tried to plug in the headphones today and i am facing the same problem only this time it atleast goes into safe mode.
I have uninstalled all the volume hud now.
Please help what could be the cause.

Thank you
Harsh Maniyar

**Comment by xMilesManx** [comment] 2019-04-13 13:44
Again, this is NOT an issue with the jailbreak code itself. 

Your issue is caused by a package you downloaded and installed from cydia. 

This really isn’t a place for support for your jailbreak problems. This is for issues with the unc0ver code itself. 

I would suggest you restore rootFS and start over. Don’t go installing a bunch of stuff if you don’t know if they work or not. 

Please close this as it is cluttering up the github.

**Closed** 2019-04-13 13:45 UTC
