### ISSUE TITLE
Phone freezes and reboots when refreshing sources

### ISSUE THREAD

**Issue by tigerban** [pwn20wndstuff/Undecimus#634] opened 2019-03-01 10:49 UTC
iOS 12.1.1 iPhone X, phone freezes then reboots, this happens random times when opening Cydia and sources refresh, or when adding or removing a source. This happened with every release, even now on the last beta happens too. With or without tweaks. 

Everytime with this Crash log:

Date: 2019-03-01 10:38:00 +0000
Bundle id: com.apple.springboard
Exception type: NSUnknownKeyException
Reason: [<SBDashBoardView 0x143ada320> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _proudLockIconView.
Parent symbol: Foundation - 0x00000001d0e44440 <redacted> + 268

**Comment by Cryptiiiic** [comment] 2019-03-01 16:46
@tigerban Head over to #409 .

**Comment by Cryptiiiic** [comment] 2019-03-01 16:46
Duplicate of #409 , so closing.

**Closed by Cryptiiiic** 2019-03-01 16:46 UTC
