### ISSUE TITLE
Messages app crashes when using the audio recording feature

### ISSUE THREAD

**Issue by ethanm10** [pwn20wndstuff/Undecimus#847] opened 2019-03-24 16:06 UTC
I am on the latest version of Unc0ver
*This happened before I installed any tweaks so I am positive Unc0ver is the problem and not a tweak

**Comment by ethanm10** [comment] 2019-03-24 16:06
*iPhone X iOS 12.1.1

**Comment by WalshyDev** [comment] 2019-03-24 16:08
Dupe of #803

**Comment by igsony** [comment] 2019-03-24 23:39
the same....b46 with   iPhone X  （iPhone 10,3)😭

**Closed** 2020-03-28 12:41 UTC
