### ISSUE TITLE
Install part 2 IOS 12.1.2

### ISSUE THREAD

**Issue by aphauger** [pwn20wndstuff/Undecimus#424] opened 2019-02-23 10:57 UTC
Hi i Cant install it says [-] task_swap_mach_voucher returner 46: (os/kern) service NOT supported

Plz help me 
Best regards Andreas

**Comment by aphauger** [comment] 2019-02-23 10:59
And when I just let it do it’s thing the app crashes

**Comment by GraysonMartin** [comment] 2019-02-23 22:12
Having this issue as well on iPhone 7 Plus running 12.1.2 with unc0ver versions b29-b31 (I've tried them all). Please help. Thanks

**Comment by Cryptiiiic** [comment] 2019-02-28 01:19
Duplicate of #407 , so closing.

**Closed by Cryptiiiic** 2019-02-28 01:19 UTC
Labels: duplicate
