### ISSUE TITLE
task_swap_mach_voucher returned 46: (os/kern) service not supported

### ISSUE THREAD

**Issue by batboy710** [pwn20wndstuff/Undecimus#511] opened 2019-02-24 19:57 UTC
Cant Jailbreak iPhone 7 running 12.1.2
[diagnostics.plist.zip](https://github.com/pwn20wndstuff/Undecimus/files/2898331/diagnostics.plist.zip)

**Comment by clarityzzz** [comment] 2019-02-24 20:24
I see you're running a beta firmware ( first beta of 12.1.2 ).
That might be the issue.
It definitely looks like it which is strange.

**Comment by batboy710** [comment] 2019-02-24 20:26
Umm are you sure? I’m running the normal public version of iOS 12.1.2, normal OTA update without any developer profiles/certificates

**Comment by clarityzzz** [comment] 2019-02-24 20:28
@batboy710 what build number is shown on your settings?
voucher_swap reports it as 16D5024a, which is the first public beta of 12.1.2, not the final release afaik?

**Comment by batboy710** [comment] 2019-02-24 20:32
The build number is in fact 16D5024a but I don’t recall participating in the public beta testing of iOS. I have no idea how I somehow have the beta version.

**Comment by batboy710** [comment] 2019-02-24 20:32
Is there a fix?

**Comment by batboy710** [comment] 2019-02-24 20:32
I tried contacting pwn but he didn’t respond on Twitter

**Comment by clarityzzz** [comment] 2019-02-24 20:35
That's okay, you're not at fault for the OS not supporting your version.
I'm not even sure if that's the reason but it's pointing to it!
For now, and if you have blobs, I'd recommend downgrading to 12.1.1 beta 3 which we know it's supported and then going back to your version with blobs.
Another question, upon unlocking your phone, do you receive a " a new beta update is available bla bla" ?
Pwn is really busy and he's being spammed a lot. He really needs the help :P

**Comment by batboy710** [comment] 2019-02-24 20:38
Nope, no pop ups regarding a beta version. I don’t have. Blobs saved and I really don’t want to be running a beta version on my daily driver.

**Comment by clarityzzz** [comment] 2019-02-24 20:48
@batboy710 that's great to hear. I believe it's because of the OTA software then(why it has such build number - I don't know). This has been the case for past jailbreaks like evasi0n. I recommend you downgrading to 12.1.1 b3, setting nonce and future restoring back to full 12.1.2 if you wish so.

**Comment by batboy710** [comment] 2019-02-24 20:49
I can’t future restore since I don’t have my blobs saved..

**Comment by clarityzzz** [comment] 2019-02-24 20:52
Oh. If you reallyyy need to be jailbroken then, I recommend downgrading to 12.1.1 b3 then.
If you don't, I'd stay for the time being. We don't have enough reports to confirm it's because of the OTA. More diagnostics are needed.

**Comment by batboy710** [comment] 2019-02-24 20:57
Sh*t..

**Comment by tsxmichael** [comment] 2019-02-25 09:09
>Oh. If you reallyyy need to be jailbroken then, I recommend downgrading to 12.1.1 b3 then. ...

@clarityzzz @batboy710 that will work 100%

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by theLeroy** [comment] 2019-02-27 18:19
@clarityzzz @tsxmichael @batboy710  i just found out i run 16D5024a and i found it out after apple stopt sining beta 3. Wath can i do now. I must have this jailbreak. I have no blobs. For logs and more #595

**Comment by Cryptiiiic** [comment] 2019-02-28 06:52
Duplicate of #407 , so closing.

**Closed by Cryptiiiic** 2019-02-28 06:52 UTC
