### ISSUE TITLE
unc0ver crashes into Safe Mode with RSD toggled on.

### ISSUE THREAD

**Issue by CyberiumShadow** [pwn20wndstuff/Undecimus#553] opened 2019-02-26 00:59 UTC
## System Details
- unc0ver b34
- iPhone 7+
- iOS 12.1
- RootFS Restored
- Airplane Mode Enabled

#### Test 1: RootFS Restore -> Jailbreak with RSD on
After RootFS Restore, I attempted to jailbreak with **Reload System Daemons** toggled **ON**.
This successfully jailbreaks after going through the three phases of: 

1. APFS Snapshot
2. Extracting Bootstrap
3. Actually starting Cydia etc

However, this ended up in a **respring into Safe Mode.**

#### Test 2: RootFS Restore -> Jailbreak with RSD off
Same as above, RootFS Restored, but instead attempted jailbreak with **RSD** toggled **OFF*.
This successfully jailbreaks **without going into Safe Mode**

#### Test 3: Rejailbreak from Jailbroken State with RSD on
Same result as Test 2. Respring into Safe Mode

#### Test 4: Rejailbreak from Jailbroken State with RSD off
Same result as Test 1. Regular Respring with no Safe Mode Crash

#### Test 5: Rejailbreak from Stock/Jailed State with RSD on
Same result as Test 1 & 3. Results in a respring into Safe Mode.

#### Test 6: Rejailbreak from Stock/Jailed State with RSD off
Same result as Test 2 & 4. Results in regular Respring with no Safe Mode Crash

## Diagnostic Logs

1. [Test1 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903268/Test1.-.diagnostics.txt)
2. [Test2 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903269/Test2.-.diagnostics.txt)
3. [Test3 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903272/Test3.-.diagnostics.txt)
4. [Test4 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903273/Test4.-.diagnostics.txt)
5. [Test5 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903274/Test5.-.diagnostics.txt)
6. [Test6 - diagnostics.txt](https://github.com/pwn20wndstuff/Undecimus/files/2903276/Test6.-.diagnostics.txt)

**Comment by mtuan293** [comment] 2019-02-26 19:16
Same to me. 7 plus on 12.1.2. Got to safe mode quite often, even after Restore RootFS. It seems like ldrestart is still broken...

**Comment by Samgisaninja** [comment] 2019-03-04 00:57
Duplicate of #403

**Closed by Samgisaninja** 2019-03-04 00:57 UTC
