### ISSUE TITLE
Cannot Send Images on Whatsapp

### ISSUE THREAD

**Issue by Burnwood1911** [pwn20wndstuff/Undecimus#1901] opened 2020-03-26 13:00 UTC
**Describe the bug**
I am unable to send photos and videos either by camera roll, capture or forwarding media from one chat to another this issue is facing a lot of people I included on iOS 13.1.3

I have tried other uncover versions.
Restoring roots fs
0 tweaks
Jailbreak hiding tweaks 
Using duplicate ipa’s
Restore phone
Downgrade WhatsApp 

But non of these work implying the problem is with the jailbreak itself

**To Reproduce**
There are no errors just red checkmark at the right of the media in chat 

**Device (please complete the following information):**
 - iOS Version: 13.1.3
 - iOS Device: IPhone XS
 - unc0ver Version: All versions Tried

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Comment by m3rtngs** [comment] 2020-03-26 21:29
Could be a potential issue with your devices firmware or WhatsApp install, I am using latest unc0ver on my iPhone XR 13.3 and I do not have this issue.

**Comment by Cryptiiiic** [comment] 2020-03-28 01:22
Duplicate of #1744

**Closed as completed by Cryptiiiic** 2020-03-28 01:22 UTC
Labels: Bug, duplicate
