### ISSUE TITLE
Errno 2 // v1.1.0

### ISSUE THREAD

**Issue by findus500** [pwn20wndstuff/Undecimus#117] opened 2018-11-16 13:20 UTC
I have the problem if i jailbreak it stop at 37/56. Then i get the error message: Errno 2. I am at IOS 11.2.2. 
I read maybe the version 1.1.0 would work. But i can‘t find the deb. Could anyone help me?

**Comment by Cryptiiiic** [comment] 2018-11-16 16:45
@findus500 Honestly dude how the fuck are we supposed to help you if you simply only say "I get Errno 2". Please think about this for a bit. Read the error. The errno is specific to the error. Since we don't know what the error is we can't do anything to help you. Please post a screenshot or paste of the error. Lmao.

**Comment by Samgisaninja** [comment] 2018-11-16 18:47
Cryptic chill pls most people don’t know that

**Comment by findus500** [comment] 2018-11-16 21:31
>@findus500 Can you please send the “LINE” number and/or description provided in the error message?  ...

@Cryptiiiic ![GitHawk Upload by findus500](https://i.imgur.com/Eb3CN5O.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by findus500** [comment] 2018-11-16 21:31
You mean that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cryptiiiic** [comment] 2018-11-16 22:03
@Samgisaninja I said lmao.

**Comment by Samgisaninja** [comment] 2018-11-16 22:31
Duplicate of #99

**Closed by Samgisaninja** 2018-11-16 22:31 UTC
Labels: invalid, need more info
