### ISSUE TITLE
ldid failed to sign libraries - prevents gcc install

### ISSUE THREAD

**Issue by Baaleos** [pwn20wndstuff/Undecimus#1157] opened 2019-07-14 23:38 UTC
**Describe the bug**
Trying to install gcc / gnu c compiler on iphone. Unfortunately - I am blocked from installing libgcc by the 'ldid failed to sign libraries' - which then causes cydia to rollback the install.
This blocks install of gcc.

**To Reproduce**
1. Attempt to install libgcc from cydia.radare.org

**Device (please complete the following information):**
iOS 12.2
iPhone 7
Using v3.3.0~b5  (I will try with the latest tomorrow)

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
'ldid failed to sign libraries'

**Comment by salas164** [comment] 2019-09-02 05:49
Still present after rootfs

**Comment by MidnightTweaks** [comment] 2019-10-05 02:43
Did anyone find the cause/ fix for this?

**Comment by mrpras** [comment] 2019-10-20 23:24
I have this on ios12.1.4 iphone7. I just don’t install it and things seem to work okay still. I get the same error - failed to sign

**Comment by MidnightTweaks** [comment] 2019-10-21 02:44
Same...

**Closed as completed** 2020-03-28 12:51 UTC
Labels: Bug
