### ISSUE TITLE
Diagnostics unc0ver / Random reboot

### ISSUE THREAD

**Issue by ss9966ss** [pwn20wndstuff/Undecimus#1905] opened 2020-03-29 09:34 UTC
https://user-images.githubusercontent.com/28376250/77845685-78ee6800-71b9-11ea-8763-2ada68caf558.jpeg

[unc0ver diagnostics](https://mega.nz/#!V4wSDa7J)

**Comment by Cryptiiiic** [comment] 2020-03-29 21:14
Duplicate of #1897 and #1890

**Closed as completed by Cryptiiiic** 2020-03-29 21:14 UTC
Labels: duplicate
