### ISSUE TITLE
alerts on imsg stopped as of this morning

### ISSUE THREAD

**Issue by alphabeta22** [pwn20wndstuff/Undecimus#1896] opened 2020-03-24 02:12 UTC
was receiving alerts and banners up til this morning on imessage running unc0ver 4.3.1 on 13.1.1 iPhone 11 Pro Max. Rejailbroke (both with Airplane mode on, and off)iP, did ldrestart 2 times, no difference. WAS getting notified alert only if imessage was open. But not if iPhone idle, or in another app. Rejailbroke with unc0ver 4.2.1. Used same procedures to ldrestart twice. Didnt show up on 4.2.1 either. 

iOS 13.1.1
iPhone 11 Pro Max
Unc0ver 4.2.1 and 4.3.1

 - [ unknown] this is a bug others will be able to reproduce
 - [ X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ X] this issue is present after a rootfs restore
 - [ X] this issue is present on the latest version of unc0ver

unc0ver freezes when trying to obtain diagnostic data. Have to clear and restart unc0ver to check anything. As soon as something is touched in settings, it freezes again.

**Comment by Hamlock-Maneuver** [comment] 2020-03-24 06:22
list your tweaks

**Comment by alphabeta22** [comment] 2020-03-24 07:54
Boxy 4, Cylinder, icleaner, Yobun, Snowboard, appsync unified, besides the mandatory ones. All latest versions

**Comment by alphabeta22** [comment] 2020-03-24 16:56
Go figure. I have not changed ONE thing...left over night...this morning it started working again. I did miss a few phone calls, but saw one this morning and answered after seeing it..dont know if that would have triggered anything again, but at work this morning, it started working again. So I guess not a bug. Just really odd in the orders and scenarios it happened. Especially JB and re-JB after restoring rootfs yesterday. No odd tweaks, no other oddities. I do realize my 13.1.1 on iP 11 PM is unusual, but..alas, its working once again! I will close.

**Comment by alphabeta22** [comment] 2020-03-25 20:10
Wouldnt ya know it? It stopped again today. No phone tones either, like before.  List of tweaks:
AppSync Unified: 720
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
Boxy 4 (iOS 13): 4.1.1
bzip2: 1.0.6-1
CA Certs: 0.0.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b24
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
debugserver-10: 10.0.0~svn-20191106+dcaf932-1
debugserver: 10-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
file: 5.35-2
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 22.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HYI Repo Icons: 8.0.4
IconSupport: 1.11.1
IconSupportFix: 1.0.0
iOS Firmware: 13.1.1
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~b27
jbctl: 0.2.3-1
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcolorpicker: 1.6.7
libidn2: 6.1.2-1
libllvm10: 10.0.0~svn-20191106+dcaf932-1
libplist: 2.0.0-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4
Profile Directory: 0-1
readline: 8.0-1
sed: 4.5-1
shell-cmds: 118-8
SnowBoard: 1.2.87~Beta2
Substitute Support Package: 0.1~b4
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
Trust Cache Injector: 0.4~b5
UIKit Tools: 1.1.15-2
XZ Utils: 5.2.4-4
Yobun: 2.5.1

**Comment by alphabeta22** [comment] 2020-03-26 01:41
When Im in the imessage app, I get the audible alert. But nothing if Im in another app, or the phone is idle. I dont get the banner alert either. If it matters....

**Comment by Cryptiiiic** [comment] 2020-03-29 02:27
Duplicate of #1880

**Closed as completed by Cryptiiiic** 2020-03-29 02:27 UTC
Labels: Bug, duplicate
