### ISSUE TITLE
Call failed messages when making outgoing calls

### ISSUE THREAD

**Issue by jrnorton8** [pwn20wndstuff/Undecimus#1922] opened 2020-04-05 17:12 UTC

**Comment by Cryptiiiic** [comment] 2020-04-08 22:54
@jrnorton8 post unc0ver diagnostics.

**Comment by Hamlock-Maneuver** [comment] 2020-04-08 23:52
Are you using callrecorder , callbar, or any other call or voice manipulating tweak?

**Comment by jrnorton8** [comment] 2020-04-09 01:18
Initially I thought that was the issue so i removed audio recorder but the issue still persisted.The only tweak i use currently that changes the phone app is “buzz” but its only theming. See a full list of my current tweaks: 

3DTools Rus: 1.0.5k
7-zip (POSIX): 16.02-1
Adguard Unbounded: 0.0.1.1
Aerial 2: 1.0.1
Ainslie Sans (iOS13): 1.1
AirDropConfirm: 1.0.0
AirPay: 1.0
AirPort (iOS 13): 1.0
All in 1 Addons for Zeppelin: 1.0.3
All in one Respring Pack: 1.4
Amandus: 1.0.1
Ambre Weather 1: 0.0.1
Ambre Weather 2: 0.0.1
Ambre Weather 3: 0.0.2
Animatoon XS: 1.0.1
Appaze 2: 1.1k
AppList: 1.5.15
AppStore++: 0.9.9-3
AppSync Unified: 72.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional: 1:0-2
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Arch: 1.3
Assuan: 2.5.1-1
Audiomack++: 1.0.0.9
AudioSnapshotServer: 1.1.0-1+debug
AutoUnlockX: 1.0.12
Avalon Studios ( Core ): 2002
Avenir Next (iOS13): 1.0
AwesomePageDots: 1.1.3
Axla 3: 1.2
ayeKit: 1.0.1
BackupAZ 3 (iOS 10 - 13): 1.7.1k
Bai Jamjuree (iOS13): 1.0
Base Structure: 1-5
Bauhaus (iOS13): 1.0
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bladient: 1.2
BlockEmAll: 0.0.2.2
Bourne-Again SHell: 5.0.3-2
Brandon Text (iOS13): 1.0
Bronkoh (iOS13): 1.0
Bunday Clean (iOS13): 1.1
Buzz: 1.1.1
bzip2: 1.0.6-1
CA Certs: 0.0.2
Cabrito Sans (iOS13): 1.0
camerAlts: 1.1
Cask 2: 1.0.0
CastSwitcher: 1.2-3
CCMusicArtwork: 2.1.2
CCSupport: 1.2.2
Central: 1.0.6
Cephei: 1.14
Cercube for YouTube: 5.1.16
Chalkboard SE (iOS13): 1.0
CleanTabs13: 1.0.1-1
Cocon Pro (iOS13): 1.0
ColorBanners 3 Rus: 1.0.1
ColorBoard: 0.0.4
ColorFlow 5 (iOS 13): 1.0.3
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Corporative Sans Alt (iOS13): 1.0
covertCK: 1.0
Covid 19 Stats: 1.6
CracksHelper: 100.2
CTDAudioSnapshotServer: 1.0.1-2+debug
cURL: 7.65.0-1
Cydia Installer: 1.1.32~b25
Cydia Translations: 1.1.32~b1
DarkShot: 1.0
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
debugserver-10: 10.0.0~svn-20191106+dcaf932-1
debugserver: 10-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DismissProgress: 1.0.4
DLEasy: 2.9.3
dotto+: 1.0.0
Dragspring: 1.2.1
Dubai (iOS13): 1.0
DuplicatorStore: 2.0
DzMohaipa Icons: 10.3
Elate: 1.0
Encode Sans (iOS13): 1.0
Encode Sans_85% (iOS13): 1.0
EVELYN's Repo Icons: 1.1
Exo (iOS13): 1.0
file: 5.35-2
Filza File Manager: 3.7.4-12
Find Utilities: 4.6.0-2
Flame: 1.3
Flipswitch: 1.0.16~beta5
FloatingDockPlus13 Rus: 1.1.6
Gateau: 1.55
Gawk: 4.2.1-1
gettext: 0.19.8-1
Gineso (iOS13): 1.0
Glober Grotesk (iOS13): 1.0
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
GoodWiFi: 0.0~beta5a
Google Sans (iOS13): 1.0
Goose Name Tag: 1.0.1
Graphite Library: 1.1.1
grep: 3.1-1
gzip: 1.9-1
HomeBarMediaProgress: 1.8
HomePlus Beta: 0.4.9-beta
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.8.2
IconBundles: 0.2-1
IconSupport: 1.11.1
IconSupportFix: 1.0.0
Interval Sans (iOS13): 1.0
iOS Firmware: 13.3
IPA Installer Console: 3.4.1-1
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~rc1
jbctl: 0.2.3-1
KarenLocalizer: 1.0.5
KarenPrefs: 1.5
Keyboard Plus Rus: 1.0.0k
Komet Pro (iOS13): 1.0
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libbulletin: 0.1-153
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcolorpicker: 1.6.7
libconorthedev: 1.1
libCozy: 0.1.0-6+debug
libCSColorPicker: 1.0.3
libCSPreferences: 1.3.4
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libllvm10: 10.0.0~svn-20191106+dcaf932-1
libmitsuha: 0.2.0-1+debug
libMRYIPC: 1.0
libnghttp2-14: 1.38.0-1
libnotifications: 0.2-4
libpackageinfo (cokepokes): 1.1.0.1-3
libplist: 2.0.0-2
libSparkAppList: 1.0.7
libsparkcolourpicker: 0.0.26
libssh2: 1.8.0-2
libsymbolicate: 1.9.0-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
Litt13: 1.3
Locale Profiles in UTF-8: 1.0-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Evo Rus: 1.2.4
Marque: 9.4
Merlen Theme: 1.5
Metro Nova Pro (iOS13): 1.0
MImport: 0.0~beta36a
Mitsuha Forever: 1.0-2
MobileGoose: 1.3
MobileGooseModule: 1.0.2
MooreBarX13: 0.9.0~alpha1.0.7
Myriad Pro (iOS13): 1.0
Nettle: 3.4.1-1
NeutronFile Icons: 1.5
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.4
Noti-Fi: 1.0.1
OpenSSH: 8.1-1
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
OTADisabler: 0.1-7
p11-kit: 0.23.12-1
PercentTimePulsate: 1.0.0
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
PrimalFolder 2: 0.0.7
Profile Directory: 0-1
QuitAll: 1.0.1
readline: 8.0-1
repo support: 2.2
RepoFinder: 1.021
ReProvision: 0.5.2~EOL
Rocket for Instagram: 3.6.14
Rocket4Insta Crack: 1.4
RocketBootstrap: 1.0.7
RoundedModules: 1.0.2
Saw: 1.4.0
sed: 4.5-1
SF Compact (iOS13): 1.0
SF Compact Rounded (iOS13): 1.0
shell-cmds: 118-8
Sica (iOS13): 1.0
SimpleActivationActions: 0.1-1
SITUM: 1.0.3
SizeFinder: 2.0.1
SmallSiri: 1.2.2
SnowBoard Dock Extension: 1.0.11~Beta2
SnowBoard Fonts Extension: 1.0.4~Beta1
SnowBoard Icon Effects Extension: 1.0.33~Beta2
SnowBoard Icon Masks Extension: 1.0.14~Beta2
SnowBoard Labels Extension: 1.0.0~Beta1
SnowBoard Page Dots Extension: 1.0.1~Beta1
SnowBoard Preset Extension: 1.0.17~Beta2
SnowBoard Procedural Wallpapers Extension: 1.0.1~Beta1
SnowBoard Respring Extension: 1.0.1~Beta1
SnowBoard Settings Icons Extension: 1.0.18~Beta1
SnowBoard StatusBar Extension: 1.0.2~Beta1
SnowBoard: 1.2.87~Beta2
SoundCloud+: 0.0.1
Spotilife: 1.1a
Stalky: 4.1.3
Substitute Support Package: 0.1~b4
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.10
SwitchColors: 1.0.2.1
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (cokepokes): 1.5.0.1-2
TinyBanners 2 Rus: 1.0.4-3
Touch: 2.0.1
TQM-Icon: 1.2
Trust Cache Injector: 0.4~b5
tweakCompatible: 0.1.5
TweakRestrictor: 1.0.2
Twitter No Ads: 0.0.1
twttr: 1.0.5
UIKit Tools: 1.1.15-2
Uni Neue (iOS13): 1.0
UnlockSound: 1.2.11
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
URW Geometric (iOS13): 1.0
VolumePercent: 1.0
VPN Proxy Master Hack: 0.0.2
Watusi 2 for WhatsApp: 1.2.37
WatusiTools: 2.1.19
WeatherPanel: 0.4
WeatherPanelV2: 0.2
wget: 1.19.5-2
Xen HTML: 1.2.4~release
XenInfo: 2.2.9
XZ Utils: 5.2.4-4
Yobun: 2.5.1
Zebra: 1.0.7
zip: 2.32-1

**Comment by Hamlock-Maneuver** [comment] 2020-04-09 02:40
Ok you have a few things going on here that should be addressed. First thing is when you installed audiorecorder.  It also installs SimpleActivationActions.  This could be the problem. But I noticed you also have the newest RocketBootstrap1.0.7 installed.  Have you noticed reprovision having problems? This is caused by the newest RocketBootstrap 1.0.7. This could also be causing issues with other tweaks.  So before we do anything, you should downgrade to RocketBootstrap 1.0.7~beta3. This will fix reprovision and allow for signing again.  I suspect this might also fix the problem you were having.  If not, then you need to uninstall CTDAudioSnapshotServer and/or AudioSnapshotServer and see if this fixes the issue.

**Comment by Hamlock-Maneuver** [comment] 2020-04-09 02:50
Something of less importance.  You might want to get rid of this "HYI Repo Icons: 8.0.4" before you post in a help forum full of developers.  

naughty boy.  ;)

**Comment by Cryptiiiic** [comment] 2020-04-09 03:43
What are you talking about. Reprovision works fine on 1.0.7 stable rbs why would you even downgrade to beta. @Hamlock-Maneuver

**Comment by Hamlock-Maneuver** [comment] 2020-04-09 03:54
Seems to be working now.  It wasn't when it first came out.

**Comment by Hamlock-Maneuver** [comment] 2020-04-09 03:58
@jrnorton8 I did some testing with some of the tweaks you are or were using.  Did you , at some point, install Statusviz?

**Comment by jrnorton8** [comment] 2020-04-09 10:22
Yes StatusViz was installed at some point.

**Comment by Hamlock-Maneuver** [comment] 2020-04-09 11:09
ok.  uninstall libmitsuha, libCozy, CTDAudioSnapshotServer, AudioSnapshotServer and libconorthedev.   I did some thorough testing of this setup and they drain your battery really fast anyway.  But lets see if this fixes the problem.

**Comment by jrnorton8** [comment] 2020-04-09 13:04
All removed.Will provide feedback later.

**Comment by jrnorton8** [comment] 2020-04-11 05:32
Removed the suggested tweak but issue still persists after some hours.

**Comment by Cryptiiiic** [comment] 2020-04-11 08:52
@jrnorton8 Any crash logs

**Comment by jrnorton8** [comment] 2020-04-12 21:46
Sadly there are no crash logs because the app doesn’t crash...the call failed message just appears in the phone app and when it disappears it goes back to the call log screen where the attempted number was dialed :(

**Comment by Cryptiiiic** [comment] 2020-04-13 02:17
@jrnorton8 CommCenter must crash right tho?

**Comment by Cryptiiiic** [comment] 2020-04-13 09:57
**Unfortunately, to reduce issue spam/clutter, help is not provided for those who have pirate packages or repos.** I can in fact help you after you remove all your piracy. After removing all of it, please say if you still experience this call failed issue. Closing this for now. I will reopen if you still have this issue after removing all piracy and piracy repos.

**Closed as completed by Cryptiiiic** 2020-04-13 09:57 UTC
Labels: Bug, Piracy

**Comment by jrnorton8** [comment] 2020-04-14 03:35
Good thing I solved it on my own 😁😂
