### ISSUE TITLE
Cannot Send Images on Whatsapp

### ISSUE THREAD

**Issue by rajpa7el** [pwn20wndstuff/Undecimus#1821] opened 2020-02-29 19:41 UTC
Bug:
I cannot send images on whatsapp after jailbreaking . 

Device:
iOS Version: 13.1.3
iOS Device: iPhone XR
unc0ver Version: 4.2.1

**Comment by rafaelwcl** [comment] 2020-03-03 15:38
Same problem on my iphone Xr ios 13.1.2 unc0ver v4.2.1... can’t send pictures or videos on whatsapp

**Comment by Cryptiiiic** [comment] 2020-03-28 01:20
Duplicate of #1744

**Closed as completed by Cryptiiiic** 2020-03-28 01:20 UTC
Labels: Bug, duplicate
