### ISSUE TITLE
App Crash doesn't reopen. iPhone X A1901 iOS 11.4b3

### ISSUE THREAD

**Issue by PlunkettSean** [pwn20wndstuff/Undecimus#47] opened 2018-10-18 16:02 UTC
While attempting to Jailbreak. After pressing the "Jailbreak" Button the unc0ver app crashed the device. Then when trying to reopen the app it crashes before it can load anything but a white screen. in order to get the app back open is to download it again. Never gets pas (1/48).
This is using the latest version R7.
Steps such as Siri off, Airplane mode off, Find My iPhone off and having the passcode off. All result in the same problem as stated above.

Note: I am coming from an Electra Jailbreak.

**Comment by Cryptiiiic** [comment] 2018-10-18 16:08
This isn't an issue with RC7, where did you install the app from?

**Comment by PlunkettSean** [comment] 2018-10-18 16:17
Tweakbox

**Comment by PlunkettSean** [comment] 2018-10-18 16:17
Should I use Cydia impactor and see if that works?

**Comment by PlunkettSean** [comment] 2018-10-18 16:33
Will do and will report the result. will be a few hours though.

**Comment by Samgisaninja** [comment] 2018-10-18 18:52
This is a known issue and duplicate of #14. I think cryptic thinks 14 was fixed in RC7, but it’s still present.

**Closed by Samgisaninja** 2018-10-18 18:52 UTC
Labels: invalid, wontfix
