### ISSUE TITLE
iPhone XR unc0ver 4.0.2 ECID always 0x0

### ISSUE THREAD

**Issue by andre104623** [pwn20wndstuff/Undecimus#1750] opened 2020-02-19 11:56 UTC
As the title says when I first jailbroke last week (I had a private beta build) my ECID always read the same 0x102something but was always the same. I didn’t update till 4.0.1 came out ever since 0x0 I mean it doesn’t seem to do anything it still jailbreaks just fine and a lot faster but I feel it should be there I could try to put it in myself I took a screenshot when I was trying to help another person here but I’m worried it will mess up my jailbreak and I have a lot of stuff installed 

Is this something to worry about oh and if I reinstall the beta build it will say 0x0 also wtf

**Comment by Hauteknits** [comment] 2020-02-23 04:09
https://twitter.com/pwn20wnd/status/1230595794429890560?s=21
https://twitter.com/razmashat/status/1230959939885109253?s=21

This is a known issue and will likely be resolved in the next couple days.

**Comment by Hauteknits** [comment] 2020-02-23 04:09
Duplicate of #1701

**Closed as completed** 2020-03-28 13:09 UTC
Labels: Bug
