### ISSUE TITLE
Unc0ver 2.2.3 is also failing to extract bootstrap

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#297] opened 2019-01-31 21:30 UTC
Every version I have tried so far is giving the same error, I still have had no help or no replies on how to fix or what’s going on :(

**Comment by coenkcore** [comment] 2019-02-01 00:01
Try to restore rootFS first, then try to jailbreak again.

**Comment by sbingner** [comment] 2019-02-01 08:51
Duplicate of #290

**Closed by sbingner** 2019-02-01 08:51 UTC
