### ISSUE TITLE
iPhone XR 13.3 Constant Panic Rebooting

### ISSUE THREAD

**Issue by m3rtngs** [pwn20wndstuff/Undecimus#1899] opened 2020-03-24 23:56 UTC
**Describe the bug**
Past few months my device has been unable to go 24 hours without panicking and rebooting. A few days ago I decided to come down on the bug myself because I noticed that it wouldn't happen when I have any tweaks installed. I started by installing some tweaks only and noticed that if I have a tweak that bypasses jailbreak detection (e.g. Shadow) and Snapchat on my device, it causes the device to panic and reboot randomly (whether or not I am currently on Snapchat). Past few days I have been running my device without Snapchat installed AND without any jailbreak bypasses and I have been having the smoothest experience so far.

**To Reproduce**
1. Have Snapchat and a jailbreak bypass on your device (e.g. Shadow)
2. Use your phone throughout the whole day and it eventually panics and reboots.

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/f77eaFMh

**Comment by Hamlock-Maneuver** [comment] 2020-03-25 17:03
It's hilarious when you see people finally starting to understand what we have been telling you guys the entire time.  Congrats on getting it.  Please spread the word.

**Comment by m3rtngs** [comment] 2020-03-25 23:08
What do you mean?

**Comment by Cryptiiiic** [comment] 2020-03-27 09:18
@MertLightz please post your unc0ver diagnostics.

@Hamlock-Maneuver what are you even talking about.

**Comment by m3rtngs** [comment] 2020-03-27 11:21
@Cryptiiiic where can I find that?

**Comment by liyiecho** [comment] 2020-03-27 11:48
unc0ver->settings->share diagnostics data, I think

**Comment by m3rtngs** [comment] 2020-03-27 12:10
@liyiecho Thank you.
@Cryptiiiic Here's a link to the diagnostics file.

https://drive.google.com/open?id=1oIbvlWyO-r_f5V5kQesJlknbgbfs7_xG

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:34
What am I talking about?  Its funny that you say that.  Its also funny that you are asking this person for some diagnostic log, after he has already said he found the problem.  What I was talking about is tweaks.  It always comes back to tweaks.  Not the unc0ver jailbreak that everyone seems to want to blame for everything happening to their device.  Like most of us have said from the very beginning.  It's your tweaks.

**Comment by Cryptiiiic** [comment] 2020-03-27 21:39
@Hamlock-Maneuver No need to be rude. That's literally what I'm doing, clearly this 870 issue clusterfuck of all non u0 related issues. I need the diagnostics because it contain package list(tweak list). Then I'll compare to others with the same exact issue. Yes its probably caused by shadow because its not updated for 13 yet but some people may not have shadow and still have a panic issue. I'm just data collecting to get solid evidence and a solid culprit. I always blame tweaks and user error over unc0ver anyday.

**Comment by Cryptiiiic** [comment] 2020-03-27 21:40
@MertLightz Uninstall shadow, it isn't updated for 13 yet afaik. Use choicy to bypass snapchat jailbreak detection.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:43
Incase you missed it, and it looks like you have.  It's the jailbreak detection bypass tweaks thats causing the problem.  Nobody being rude bro.  You just taking it that way.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:46
The other thing I was pointing out is that the OP is the one who came up with the solution.   The very same one you are trying to help...

**Comment by Cryptiiiic** [comment] 2020-03-27 21:49
@Hamlock-Maneuver I'm not "just taking it that way". There is a bigger picture that you aren't seeing. I can read, he needs to use choicy, he will get caught in the banwave otherwise. And choicy hasn't been reported to cause panics yet.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:49
What needs to be done is someone needs to contact the developers of said tweaks (liberty lite and other like it) and inform them of the restarts being caused by their detection bypass method.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:51
the OP already knows of said consequences, hence the reason he was using bypass tweaks in the first place.  He is looking for a solution that you can not provide. Unless of cource, you can fix the jailbreak detection yourself...

**Comment by Cryptiiiic** [comment] 2020-03-27 21:53
@Hamlock-Maneuver again, I can read. I was just offering my 2-cents methods for fixes. Is givng my 2-cents a crime now? Go ahead, solve all 870+ issues by yourself, I'm waiting. Mr 2-cents police.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:55
I think you should calm down a bit and maybe step back from this conversation for awhile.  You obviously seem upset about something, and are taking things the wrong way.

**Comment by Cryptiiiic** [comment] 2020-03-27 21:57
@Hamlock-Maneuver not upset at all, you attacked me for talking. I'm calm as fuck lmao. I'm gonna close this due to solved.

**Comment by Cryptiiiic** [comment] 2020-03-27 21:57
@MertLightz solved, so closing.

**Closed as completed by Cryptiiiic** 2020-03-27 21:57 UTC
Labels: Bug, complete

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:58
Something you should learn about chat.  We are not face to face.    Never assume emotions.

**Comment by Hamlock-Maneuver** [comment] 2020-03-27 21:59
nobody attacked you. assuming so doesn't make it real.

**Comment by m3rtngs** [comment] 2020-03-28 15:59
@Cryptiiiic Alright, thanks.
