### ISSUE TITLE
Error on step 2 of jailbreak

### ISSUE THREAD

**Issue by johnweisz2112** [pwn20wndstuff/Undecimus#465] opened 2019-02-24 05:03 UTC
I am getting the following errors step 2 of unc0ver. It crashes and resprings after listing the error about 500 times:

[+] sprayed 444019712 bytes to 11 ports in kalloc. 1024
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[+] stashed voucher pointer in thread
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported
[-] task_swap_mach_voucher returned 46: (os/kern) service not supported

iPhone X, iOS 12.1.2 with tvOS profile

Tried reinstalling, removing tvOS, I don't have OTA data, tried with airplane mode on

I have also tried disabling system daemon reloading and basically all the other settings options. No dice

**Comment by willdesigns** [comment] 2019-02-24 14:17
I'm having the exact same problem - need help

**Comment by Cryptiiiic** [comment] 2019-02-28 06:31
Duplicate of #407 , so closing.

**Closed by Cryptiiiic** 2019-02-28 06:31 UTC
