### ISSUE TITLE
Kernel panics

### ISSUE THREAD

**Issue by BaddestAssasin** [pwn20wndstuff/Undecimus#1963] opened 2020-05-22 11:54 UTC
My phone has random kernel panics with unc0ver. I know it’s not a tweak because on checkra1n this never happens.
**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: ip7
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here. Their are no crash log anywhere

**Comment by Cryptiiiic** [comment] 2020-05-22 23:36
Duplicate of #1890

**Closed as completed by Cryptiiiic** 2020-05-22 23:36 UTC
Labels: duplicate
