### ISSUE TITLE
Stability issues with Cydia Substrate on iOS 12

### ISSUE THREAD

**Issue by pwn20wndstuff** [pwn20wndstuff/Undecimus#960] opened 2019-04-17 18:54 UTC
I am submitting this issue to provide details about the issues and working ways of reproducing them to make it easier for @saurik to fix them - If you have your own discoveries, reply to this issue with them.

- Hooking securityd causes the entire system to freeze (Reproduce: Install unc0ver v3.0.0~b48 from the releases page, install TetherMe or any tweak that hooks securityd, restart securityd)
- Substrate's bootstrap_look_up hook seems to not be working properly, kernel occasionally complains about it in the syslog (e.g. `iPhone kernel(Sandbox)[0] <Error>: Sandbox: lockdownd(379) deny(1) mach-lookup cy:com.saurik.substrated`)
- Running ldrestart occasionally causes the device to freeze and reboot
- Jetsam is able to kill substrated under low memory conditions (e.g. https://ghostbin.com/paste/x8ckw)
- Running this command will almost certainly freeze and crash the entire system on iOS 12 `/usr/libexec/substrate && launchctl unload /System/Library/LaunchDaemons/com.apple.backboardd.plist && ldrestart; launchctl load /System/Library/LaunchDaemons/com.apple.backboardd.plist`

**Comment by soum91** [comment] 2019-04-26 16:32
So what is the state of the progress/future of this issue since Saurik has left the scene? I guess fixing these will solve the random reboots/kernel panic still present there with the latest u0.

**Comment by NickyDee** [comment] 2019-07-13 23:23
unc0ver jailbreak Beta 5 worked fine but with beta 6 & 7 I get this......  ERROR: unable to start cydia substrate.
Any help would be appreciated. 

![image](https://user-images.githubusercontent.com/48070833/61177453-b4052880-a5a3-11e9-9439-5c40add76716.png)

**Comment by Aa300300** [comment] 2019-09-01 16:51
> So what is the state of the progress/future of this issue since Saurik has left the scene, Pwn? I guess fixing these will solve the random reboots/kernel panic still present there with the latest u0.

**Comment by Lessica** [comment] 2019-09-23 11:23
unc0ver 3.6.2+1
I have many iPhone 6S + iOS 12.4 (exp: Sock Puppet 3.0) in app testing production.

1. random system freeze (need force shutdown)
2. re-jailbreak: unable to start substrate
3. app stuck at launch screen, no responding
4. cannot reload daemons (sshd), even "killall" got *killed* after a few hours

Once reboot & jailbreak, everything back to normal and perfect.
I don't know how to reproduce. All problems appear in a sudden, just after a few hours after jailbreak.

**Comment by richwincott** [comment] 2019-09-29 14:23
Similar but with Substitute - #1558

**Comment by azooz12312312312** [comment] 2020-03-11 04:12
![86368178-D7FF-40E8-85E3-1180D7CCFA80](https://user-images.githubusercontent.com/61816553/76381825-ab016c80-6367-11ea-932b-08d75fcb042d.png)

**Comment by azooz12312312312** [comment] 2020-03-11 04:34
Duplicate of #

**Closed** 2020-03-28 12:42 UTC
