### ISSUE TITLE
iOS 11.2.1 | ErrNo: 2 Failed to inject library | Failed to spawn jailbreakd

### ISSUE THREAD

**Issue by s4tan** [pwn20wndstuff/Undecimus#107] opened 2018-11-07 14:34 UTC
[Here's a Screenshot of the error](https://www.bilder-upload.eu/upload/43c1f4-1541600897.png)

I'm getting this error since I updated unc0ver to v1.1.4. I can't downgrade to the old working version, because I can't find the IPAs here. But I was hoping to find a solution for the newest version.

**I have an iPhone 8 64GB, running on 11.2.1**

Here's the diagnostics.plist generated from unc0ver:
[MEGA.NZ](https://mega.nz/#!8Xpw2I6Z!xVUhyESmevB0i9mLSdfTXUJJydVZpFSJcQ233xXOiI4)

**Comment by Samgisaninja** [comment] 2018-11-07 16:43
Closed. Duplicate of #99

**Closed by Samgisaninja** 2018-11-07 16:43 UTC
