### ISSUE TITLE
unc0ver 3.0.0 b41 still has issues with a respring loop with System Daemons enabled, Phone reboots. 

### ISSUE THREAD

**Issue by dallasgroot** [pwn20wndstuff/Undecimus#717] opened 2019-03-05 21:44 UTC
**Describe the bug**
I've never successfully been able to jailbreak my iPhone X 12.1.2 with Reload System Daemons enabled. It will go in an endless spinning wheel (half of it is faded) and spins for a couple mins and then restarts. 
 **To Reproduce**
1. Go to 'unc0ver app'
2. Click on 'Settings'
3. Scroll down to 'Reload System Daemons'
4. Enable
5. Click on Jailbreak
6. unsucess (last little bit from the console log) https://pastebin.com/pmHJGHz1

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone X GSM
 - unc0ver Version: 3.0.0 41b

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce - I seem to always have bad luck
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
https://pastebin.com/pmHJGHz1

**Comment by Mas9311** [comment] 2019-03-05 21:57
Please disable the Reload System Daemons option and report back.

**Comment by dallasgroot** [comment] 2019-03-05 21:58
This has always worked for me since the release of Cydia came bundled with it, I'll provide a log for it

**Comment by dallasgroot** [comment] 2019-03-06 01:16
unfortunately this never difficult for me either sad face

	
Dallas Groot
about.me/dallasgroot

**Comment by king4q** [comment] 2019-03-06 03:12
Update Rocketbootstrap & Preference loader from http://rpetri.ch/repo, @Cryptiiiic please close this issue.

**Comment by dallasgroot** [comment] 2019-03-06 04:37
No, don't close this issue because it hasn't been fused yet. Rather than assuming I haven't  done that yet is going to solve any thing is the reason why fixes don't be made. I'm willing to help with this project, but if people like you exist, well it's going to be hard. There. Thais my update on this. 

	
Dallas Groot
about.me/dallasgroot

**Comment by kurtbain250** [comment] 2019-03-06 06:56
Hello fellow British Columbian (fist bump)
iPhone X 12.1.2 here, still experiencing the same issue described even after the latest rocket bootstraps updates (but i havent tried rootfs restore yet).
I have multiple devices, my iphone 6S 12.1.1 with 15+ tweaks did also experience the same issues until the rocket bootstrap update, now it does work with reload system data (ldrestart) enabled but the device goes into safemode first until i respring. After the respring its fine. Same results when running ldrestart from mterminal.
Tonight I just futurerestored an iphone 5S to 12.0.1, jailbroke latest unc0ver beta 41 (so fast btw!) with nothing installed i added rocket bootstrap from rpeti.ch repo and rebooted, ran the jailbreak and it worked like a charm. Then installed mterminal and ran ldrestart, worked like a charm. 
So
Is it a common tweak that is causing the issue 
OR is it an iPhone X (maybe 8) exclusive bug with rocket bootstrap or another tweak.
My next step was to uninstall every tweak one by one on the iphone x till i find it but i see youve marked that after a rootfs restore the issue still persisted so maybe ill skip the uninstall each tweak and just rootfs restore then try again from scratch. 
Ill happily post back with my response tomorrow if the mods leave this open. 

As for pwn, im not sure if this would be considered his or unc0vers issue so i do understand if he closes the issue. But if he reads this may i suggest leaving it open so others can share till we bury this bug once and for all?

**Comment by mgfjxxiexiaolong** [comment] 2019-03-06 10:02
I got this problem too, b41 on iphone6s iOS12.0.1

**Comment by j04cfu457** [comment] 2019-03-06 13:06
I am experiencing the same error with b41 on iphone SE ioS12.0.1. Sure works with the system deamons reload turned off. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kurtbain250** [comment] 2019-03-07 03:26
iPhone 6S or(+), 6, SE, 5S users, please uninstall BegoneCIA (iOS 11 and 12) from repo.nepeta.me, then update to the latest unc0ver beta 42, reboot and jailbreak with reload system daemons enabled and report back. 
This should fix your issue.... 
IF it doesn't, try uninstalling snowboard (yes even if its the latest version released today) and retry the same steps. 
Uninstalling BegoneCIA from my iPhone 6S solved the reload system daemon issue with that particular device.
And yes, i can reinstall BegoneCIA and replicate the issue over again, so ill send the dev a bug report and we can call this one squashed. 
Users with pre iphone 7 devices experiencing this issue should review the tweaks they have installed on their devices then try uninstalling them one by one till the issue is resolved.
 
Now onto iPhone X. Uninstalling BegoneCIA did not solve my issue. Im still not sure if this is a device specific thing or what. Tonight ill try uninstalling a few more tweaks but the process is slow give me a bit. I still beleive this is a tweak issue but will see.

P.S Thanks pwn and team for keeping this open! and umm thanks for the A9 MS support!! Seriously, rebooting over and over trying to debug this would of been a nightmare on VS, MS is so fast and reliable! Perfect timing for that release!

**Comment by drpoutine** [comment] 2019-03-09 22:53
iPhone X 10,6 same issue. Ldrestart seems to be broken. RBS is updated thru rpetrichs repo. Only workaround at the moment seems to be to disable ldrestart. But the phone will eventually crash on itself and apps will stop responding until a reboot is performed. Not sure what's causing this bug

**Comment by king4q** [comment] 2019-03-09 23:49
@sbingner @pwn20wndstuff

**Comment by coenkcore** [comment] 2019-03-10 13:51
Try using 3.0.0~b43
- run rooftfs restore
- jailbreak again after rootfs restore succes
- make sure you run jailbreak with airplane mode on
- becareful with not compatile tweak it's cause your device random respring/going to safemode

**Comment by drpoutine** [comment] 2019-03-11 05:53
The issue began on b43. No new tweaks were installed on my end.

**Comment by nuno10costa** [comment] 2019-03-12 16:51
Just figure out the issue.

I suggest who is facing this same problem to go to icleaner pro and disable all tweaks and test the jailbreak with RSD enabled. For me it worked, so it's clear then the issue was with a certain tweak.
Just try enabling them one by one in order to understand which one is causing the problem.

**Comment by Pflegusch** [comment] 2019-04-29 18:06
> 
> 
> Just figured out the issue.
> 
> I suggest who is facing this same problem to go to icleaner pro and disable all tweaks and test the jailbreak with RSD enabled. For me it worked, so it's clear then the issue was with a certain tweak.
> Just try enabling them one by one in order to understand which one is causing the problem.

Worked for me, thank you!

**Closed** 2020-03-28 12:39 UTC
Labels: bug
