### ISSUE TITLE
[Debugging] Respring Crash upon enabling 'Reload System Daemons'

### ISSUE THREAD

**Issue by TempAccountNull** [pwn20wndstuff/Undecimus#608] opened 2019-02-28 02:14 UTC
### Tweaks which can cause these respring loops to happen without disabling system daemons
- RBS (RocketBootStrap by rpetrich) https://github.com/rpetrich/RocketBootstrap 1.06
- AFC2 (Apple File Conduit "2" (arm64/KPPLess) https://github.com/Cannathea/afc2d-arm64 1.02

### Respring loop could be caused by WDT (WatchDogTimer) failing to recover within 20 seconds
Why:
1. It kills the process 
2. Kills the daemons 
3. Then the device not knowing what to do at this point panics
4. Device reboots.

### Kernel Panic Log
> **panicString: "Debugger message: WDT timeout"**
> 91s ago: 
> 1009b50 1009f9fd0ce63 1009r6b86f000 1001m
> 989fd46ab242 900m 
> 900nffffffff 868f49d4ae5a 
> 867f9fd0ce63 800m 700m 600m 
> 575f49d4ae5a 574f9fd0ce63 500m 400m
> 373f5e0489a 373f9fd0ce63 349f7038d128 300m
> 256f49d4ae5a 239f9fd0ce63 200m 100m
> 9f49d4ae5a 0f5e0489a 0m

> **Kernel Panic Message**
> bug_type :210
> timestamp: 2019-02-27 18:07:28.42 -0600
> os_version:iPhone OS 12.1 (16B92)
> incident_id: 4C79BDDC-D2F2-4964-B091-AD25A64128CF
> build: iPhone OS 12.1 (16B92)
> product: iPhone8,1
> kernel: Darwin Kernel Version 18.2.0: Tue Oct 16 21:02:23 PDT 2018; root:xnu-4903.222.5 RELEASE_ARM64_S8000
> incident: 4C79BDDC-D2F2-4964-B091-AD25A64128CF
> crashReporterKey: 8f396ec0b286be43fafa189466554ec6faeb6ce8
> date: 2019-02-27 18:07:27.12 -0600
> Memory ID: 0xff 
> OS version: 16B92 
> Kernel version: Darwin Kernel Version 18.2.0: Tue Oct 16 21:02:23 PDT 2018; root:xnu-4903.222.5~1\/RELEASE_ARM64_S8000 KernelCache 
> UUID: 64996F4A2FB57AF331656210F3226CC5 
> Kernel UUID: 4258120F-EFFA-3E49-8141-06E49623FFEF 
> iBoot version: iBoot-4513.220.100
> secure boot?: YES
> Paniclog version: 11
> Kernel slide: 0x000000001da00000
> Kernel text base: 0xfffffff024a04000
> Epoch Time: sec usec Boot: 
> 0x5c772627 0x000724e8 
> Sleep: 0x00000000 0x00000000
> Wake: 0x00000000 0x00000000
> Calendar: 0x5c7726ef 0x0006f599
> Total cpu_usage: 13121223 
> Thread task pri cpu_usage 0xffffffe0004ee450 
> kernel_task 0 5051907 0xffffffe0008ee980 
> kernel_task 0 7039297
> Panicked task 0xffffffe0004c10e0: 9191 pages 204 threads: 
> pid 0: kernel_task 
> Panicked thread: 0xffffffe0004ee450 
> backtrace: 0xffffffe037d5f570 
> tid: 102
> lr: 0xfffffff024bc02e4
> fp: 0xffffffe037d5f6a0
> lr: 0xfffffff024aa15c4
> fp: 0xffffffe037d5f6b0
> lr: 0xfffffff024ad2804
> fp: 0xffffffe037d5fa30 
> lr: 0xfffffff023bc565c
> fp: 0xffffffe037d5fee0
> lr: 0xfffffff024768598
> fp: 0xffffffe037d5ff10
> lr: 0xfffffff0244a24a4
> fp: 0xffffffe037d5ffa0 
> lr: 0xfffffff024f7dec4
> fp: 0xffffffe037d5ffb0
> lr: 0xfffffff024bc1260
> fp: 0xffffffe037d5ffe0
> lr: 0xfffffff024aa1614
> fp: 0xffffffe037d5fff0
> lr: 0xfffffff024ae8b74
> fp: 0xffffffe03d2dbc90
> lr: 0xfffffff024aa7454
> fp: 0x0000000000000000
> panicFlags : 0x2
> otherString : ** Stackshot Succeeded ** Bytes Traced 125296 **
> memoryStatus:
> compressorSize:19
> compressions:30845
> decompressions:8373
> busyBufferCount:0
> pageSize:16384
> memoryPressure:false
> memoryPages:
> active:17286
> throttled:0
> fileBacked:46133
> wired:11443
> purgeable:8
> inactive:17804
> free:62507
> speculative:13473

### Reboot Log
> bug_type: 115
> timestamp: 2019-02-27 18:10:55.71 -0600
> name: Reset count
> os_version: iPhone OS 12.1 (16B92)
> incident_id: C1BE338B-6A0D-4135-8354-6703BE537344}
> Incident Identifier: C1BE338B-6A0D-4135-8354-6703BE537344
> CrashReporter Key: 8f396ec0b286be43fafa189466554ec6faeb6ce8
> Date: 2019-02-27 18:10:55.37 -0600
> Reset count: 0x1
> Boot failure count: 0x0
> Boot faults: 
> Boot stage: 0x0
> Boot app: 2681261667 / 0x9FD0CE63

### Raw Logs from '/var/mobile/Library/CrashReporter'
- Kernel Panic Log 'Error 210'
[panic-full-2019-02-27-181056.159.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2913105/panic-full-2019-02-27-181056.159.ips.txt)

- Reboot log 'Error: 115'
[ResetCounter-2019-02-27-181055.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/2913137/ResetCounter-2019-02-27-181055.ips.txt)

**Comment by airsquared** [comment] 2019-02-28 18:23
A temporary fix for this is to disable "Reload System Daemons" then after respringing run `ldrestart` manually(from NewTerm2 or SSH).

**Comment by TempAccountNull** [comment] 2019-03-02 03:19
how would one load ldrestart from term?

**Comment by josearg** [comment] 2019-03-02 19:10
I always do the jailbreak disabling reload system daemons and after that I do a LDRestart and all is working fine for me. And the jailbreaks is successful always. I use PowerSelector tweak to easily perform the LDRestart.

**Comment by TempAccountNull** [comment] 2019-03-02 21:37
@josearg That's the issue, you shouldn't have to do any of that. This is presented to figure out what maybe going on 'behind the scenes'. WatchDogTimer seems to be killing the process. (On my end) anyways.

**Comment by TempAccountNull** [comment] 2019-03-03 22:41
Issue doesn't seem to be present in the recent version. But, further testing will have to be done to conclude if this is true or not.

**Comment by Samgisaninja** [comment] 2019-03-04 00:58
Duplicate of #403

**Closed by Samgisaninja** 2019-03-04 00:58 UTC

**Comment by TempAccountNull** [comment] 2019-03-06 03:17
Issue has been moderately fixed. Resprings for sometime prior to coming back then phone restarts if idle.
