### ISSUE TITLE
Bad CPU type in executable 

### ISSUE THREAD

**Issue by buroa** [pwn20wndstuff/Undecimus#191] opened 2018-12-31 15:34 UTC
Some of my system executables, like killall, have a bad CPU type (I’m guessing I installed something 32 bit maybe?)

Anyways, is there any way I can fix these issues?

**Comment by zsolt-halo** [comment] 2019-01-03 13:35
#200

**Comment by Cryptiiiic** [comment] 2019-01-07 17:33
Duplicate of #200 so closing.

**Closed by Cryptiiiic** 2019-01-07 17:33 UTC
Labels: duplicate
