### ISSUE TITLE
Freezing, random respring and kernel panic

### ISSUE THREAD

**Issue by soum91** [pwn20wndstuff/Undecimus#137] opened 2018-12-03 16:00 UTC
I’m opening the issue with the fear that Sam would call me eta nagger as last time and close the issue.
Unc0ver journey was going really smooth(except battery drain) up until the v.2 prerelease. Now I’m getting the essence of Electra. Having app freezes, random respring and ultimately reboots from kernel panic. Within the four days of installation I had 3 kernel panics and lots of freezes and resprings. My setup has not been changed from pre v.2 time. 

Attaching 3 panic logs below 

https://www.icloud.com/iclouddrive/0PaNDaakWVjaruMuAu-QSikgQ#panic-full-2018-11-30-020045
https://pastebin.com/fv0XMMr4
https://pastebin.com/dFZTCuCk

Not all sb crashes/resprings produce crash log. Luckily just springboard crashed which also produced crash log. Below I’m attaching that too
https://pastebin.com/JPW4DZX4

Yet another panic, attaching that too.
https://pastebin.com/6aqbiBnj

**Comment by pixelomer** [comment] 2018-12-03 17:43
Just a reminder. It's called **a prerelease** for a reason.

**Comment by soum91** [comment] 2018-12-03 18:13
@pixelome just because it’s prerelease doesn’t mean you can’t let the Dev know about the issues. I’m not complaining, just doing what Pwn20wnd said. He himself said to report him any issues one experiencing.

**Comment by syto203** [comment] 2018-12-03 22:58
Try disabling all your tweaks and wait a day or two while still using the device then enable them one by one over the course of a week until you find whatever is causing it.

**Comment by soum91** [comment] 2018-12-04 08:18
@syto203, I guess you didn’t read it! My setup has NOT been changed since v.1.1.4. There’s nothing new except the updated unc0ver!

**Comment by soum91** [comment] 2018-12-04 08:35
@luisgeraldes32, try other signing service when this happens. Or you can reinstall from current one since is said to be fixed. EL will most of the time failed into reboot, always try to use MP.

**Comment by soum91** [comment] 2018-12-05 17:59
@pwn20wndstuff are you aware of the issue? Are you doing anything regarding this? I had 4 panics within the 6 days of installation.(on other two days I forced rebooted due to freeze.)

**Comment by Samgisaninja** [comment] 2018-12-06 20:41
so, 
1. [I apologized and asked that you further explain, but you never replied](https://github.com/pwn20wndstuff/Undecimus/issues/114#issuecomment-439303078)
2. We know there are freezes. We've done our best to prevent them, and when they happen, typically the device resprings after a minute (this is our best way of mitigating the issue). This is a duplicate of #12 and is closed *for that reason*. 

#12 is a known issue with no fix other than removing jailbreakd, which is exactly what I commented on the last issue you created. This happens automatically when Substrate is installed, however we have no control of when saurik decides to publicly release substrate for iOS 11.

**Closed by Samgisaninja** 2018-12-06 20:41 UTC

**Comment by soum91** [comment] 2018-12-07 08:41
@Samgisaninja, well I have given up with the battery drain issue and taken that as perk(??) of jailbreaking. I won’t  complain again about since you guys offering the better jailbreak than any other jailbreak with constant support and that’s for free. All all should be grateful for that. And I apologize for my last reply being a bit harsh.

Now about the freeze, I understand that it’s being caused by jailbreakd and there is not really you guys can do(except you guys release another ‘substitute’ to substrate) until Saurik releases. But is the same reason that my phone is kernel panicking? Because I had the highest uptime with the v1.1.4 that I ever had with iOS 11 jailbreak. That’s why I thought it’s somehow related to the latest update. This kernel panic is getting out of hand because yesterday within a short period of time I had two panics.

**Comment by Samgisaninja** [comment] 2018-12-07 14:25
Kernel panics shouldn’t occur with kppless jailbreaks. I don’t know why that’s happening for you. 

We aren’t releasing any further updates to substitute because we have a fully working and stable build of substrate, so it wouldn’t make sense for us to update a package that’s already deprecated
