### ISSUE TITLE
iPhone XR iOS 13.3 Panic Reboots (Again)

### ISSUE THREAD

**Issue by m3rtngs** [pwn20wndstuff/Undecimus#1906] opened 2020-03-30 01:12 UTC
**Describe the bug**
Second time posting this due to it not being fixed for me. Past few months my device has been unable to go 24 hours without panicking and rebooting. A few days ago I decided to come down on the bug myself because I noticed that it wouldn't happen when I have any tweaks installed. I started by installing some tweaks only and noticed that if I have a tweak that bypasses jailbreak detection (e.g. Shadow) and Snapchat on my device, it causes the device to panic and reboot randomly (whether or not I am currently on Snapchat). Past few days I have been running my device without Snapchat installed AND without any jailbreak bypasses and I have been having the smoothest experience so far. I have tested with both Tweaks Manager and Choicy (running together) and my device has carried on to panic and reboot hence why I am opening this bug report a second time.

**To Reproduce**
1. Have Snapchat and a jailbreak bypass on your device (e.g. Shadow)
2. Use your phone throughout the whole day and it eventually panics and reboots.-

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone XR
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
Panic Full: https://drive.google.com/open?id=1wiJVGUNlGsxbwLz_Yun2g_yI9a1XE76W
Unc0ver Diagnostics: https://drive.google.com/open?id=1Z1nLFR-pKIJRLgdX54IuoUXRnEN_fTou

**Comment by Cryptiiiic** [comment] 2020-03-30 05:07
Duplicate of #1890

**Closed as completed by Cryptiiiic** 2020-03-30 05:07 UTC
Labels: Bug, duplicate

**Comment by m3rtngs** [comment] 2020-03-31 23:29
@Cryptiiiic what can I do? Any bypass I use causes my phone to panic. I have no pirated tweaks or YouTube related tweaks.
