### ISSUE TITLE
Cannot Send Images on Whatsapp

### ISSUE THREAD

**Issue by siken2021** [pwn20wndstuff/Undecimus#1841] opened 2020-03-08 22:53 UTC
**### Cannot Send Images on Whatsapp and Stickers**

![image](https://user-images.githubusercontent.com/49955356/76172596-a8cfc000-6165-11ea-94d1-0f35d420b8b7.png)

**Device (please complete the following information):**
 - iOS Version: 13.1.3
 - iOS Device: iPhone 7
 - unc0ver Version: 4.3.1

**Comment by Cryptiiiic** [comment] 2020-03-28 01:20
Duplicate of #1744

**Closed as completed by Cryptiiiic** 2020-03-28 01:20 UTC
Labels: Bug, duplicate
