### ISSUE TITLE
Can't open latest Unc0ver 3.5.0 iOS 11.2.6 crashes immediately.

### ISSUE THREAD

**Issue by galaxy-nomad** [pwn20wndstuff/Undecimus#1269] opened 2019-08-19 00:05 UTC
After downloading the latest Unc0ver app from Tweakbox and trusting it in settings Unc0ver will not open at all. There is also no option to downgrade as the latest version is all that is offered in Tweakbox. iOS 11.2.6 iPhone 6s Unc0ver 3.5.0.

**Comment by novapays** [comment] 2019-08-19 00:15
I second this - ios 11.0 iphone 8

**Comment by AlexMerhi** [comment] 2019-08-19 00:28
Thats most likely an issue with TweakBox

Use **Cydia Impactor** to install unc0ver 
It's VERY EASY and only takes a minute or two. 
Just make sure you sign into https://appleid.apple.com and generate an "app specific password" to use for Cydia impactor

2nd Tip is to make sure you've trusted the source on Settings > General > Profiles & Device Management

**Comment by novapays** [comment] 2019-08-19 00:29
I used reprovision to install it. Then tried ignition, and tweakbox. All
have the same error on ios 11

**Comment by galaxy-nomad** [comment] 2019-08-19 00:31
I'd like to avoid impactor. I don't want my own Apple ID on the phone and I don't want to have to create a throw away apple ID. Tweakbox keeps everything streamlined and my Apple ID stays out of the picture. Also with Tweakbox everything is on device and I don't have to have my iphone tethered to my laptop.

**Comment by galaxy-nomad** [comment] 2019-08-19 01:14
EDIT: I actually installed 3.4.2 using impactor not the latest 3.5.0 so it looks like this may be an issue with Unc0ver.

@iRuthl3ss You were right. I bit the bullet and used Impactor and Unc0ver opened right up. I think there is an issue with the developer account that both Tweakbox and Ignition are using to sign the Unc0ver app. @novapays It must be the developer account they use to sign the app.

**Comment by xMilesManx** [comment] 2019-08-19 01:48
Please close this if you would. This isn’t an issue with unc0ver.

**Comment by TroX-oO** [comment] 2019-08-19 07:03
Hi,

I have the same issue, and installing unc0ver 3.5.0 with impactor did not help. It still crashes at start.
Is there any crash logs that I can browse to see what's going on ?

**Comment by novapays** [comment] 2019-08-19 07:05
have a look on my twitter as i have a post up about fixing this for ios 11
users. @ytnovapaus

**Comment by TroX-oO** [comment] 2019-08-19 07:07
No such user on twitter. Typo ?

**Comment by novapays** [comment] 2019-08-19 07:09
Ytnovapays sorry. My bad

**Comment by TroX-oO** [comment] 2019-08-19 07:17
Your link is not very trustful. But I noticed that they was not up to date with the last 3.5.0 version of unc0ver, but are still on 3.4.2. So I installed it with the official .ipa from this repo with impactor and it worked.

So there is indeed a bug with the latest 3.5.0 on iOS 11 (i'm on 11.1.2)

Thank you for your help to find the solution.

**Comment by novapays** [comment] 2019-08-19 07:20
Not my link* but i had to use this personally as 3.5.0 was crashing upon
open for me. I used this link to install 3.4.2 and i didnt have any issue.
Just a risk i was willing to take. Its not for everyone though so I
understand where you’re coming from

**Comment by novapays** [comment] 2019-08-19 07:21
After this i updated to ios 12.4

**Comment by TroX-oO** [comment] 2019-08-19 07:22
That's what i'm doing right now too ;)

This issue should still be re-openned I think.

**Comment by novapays** [comment] 2019-08-19 07:24
Honestly, im not regretting updating either. But im waiting for the next update of unc0ver as the success rates a bit iffy apparently

**Comment by xMilesManx** [comment] 2019-08-19 07:31
@TroX-oO Well no it shouldn’t. Tweakbox signing issues should not be posted here because that has nothing to do with unc0ver directly. If you are having trouble installing and running it with impactor on your device that is a completely separate issue. This issue page is already completely overwhelmed with useless “issues” and bury real genuine problems.

**Comment by TroX-oO** [comment] 2019-08-19 07:51
We are not talking about Tweakbox or any other signing issues.

We are just taking the 3.5.0 version out of the box from this repo, and installing it with cydia impactor. And then this version crashes at launch. Whereas with the 3.4.2, it works.

This as nothing to do with any other external jailbreak tool. This is totally related to unc0ver itself.
I understand that jailbreak community is on fire right now, and it's not convenient to see useless issues created. But you should definitely give some attention to this one.

(Moreover, there IS a temporary fix that is to install 3.4.2 instead of 3.5.0, so this is not the priority right now)

**Comment by xMilesManx** [comment] 2019-08-19 10:24
You said to reopen the issue. The original issue is about tweakbox. Not what you’re talking about in the comments.

**Comment by novapays** [comment] 2019-08-19 10:27
The issue is actually about 3.5.0 crashing on ios 11 devices. Yes their was a mention of tweakbox. But like i said above. Ignition, tweakbox and other signing services have got the same issue with the 3.5.0 ipa on ios 11 devices

**Comment by xMilesManx** [comment] 2019-08-19 10:40
The OP should edit the original issue then. If the issue has nothing to do with tweakbox that it shouldn’t be included as impactor is the only officially supported installation method

**Comment by galaxy-nomad** [comment] 2019-08-19 10:42
Hi guys I've reopened the issue. In the process of troubleshooting I lost track of what I was doing and I installed 3.4.2 using Impactor instead of trying for 3.5.0. So it looks like Tweakbox may not be the issue afterall? Anyway 3.4.2 worked for me so I'm avoiding even trying 3.5.0 for now.

**Comment by novapays** [comment] 2019-08-19 10:48
Probably for the best, unless you update to 12.4 like me then you’ve got no issue

**Comment by novapays** [comment] 2019-08-19 10:59
@cyberfunk, pwn released 3.5.1 to fix the issue. Have a look 🙂

**Comment by galaxy-nomad** [comment] 2019-08-19 11:13
Thanks @novapays I'll look for the update on Tweakbox😀

**Comment by c0d3z3r0** [comment] 2019-08-20 15:54
Same problem here with 11.2.2 on a iPhone 7; unc0ver instantly crashes... even with 3.5.1 and 3.5.2

**Comment by galaxy-nomad** [comment] 2019-08-20 15:57
@c0d3z3r0 Try 3.5.2 from Ignition: https://app.ignition.fun visit this address on your iOS device and download it there. That just worked for me on iOS 12.1.4 which is different than iOS 11 but that might work for you.

**Comment by c0d3z3r0** [comment] 2019-08-20 18:04
@cyberfunk thanks, I can confirm ~~3.5.2~~ 3.2.1 works (done with impactor)

Edit: typo...

**Closed as completed** 2020-03-28 13:00 UTC
Labels: Bug
